/*
Everflow Network API - Advertisers

API for managing advertisers in the Everflow platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package advertiser

import (
	"encoding/json"
)

// checks if the AdvertiserRelationshipApiKeys type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdvertiserRelationshipApiKeys{}

// AdvertiserRelationshipApiKeys struct for AdvertiserRelationshipApiKeys
type AdvertiserRelationshipApiKeys struct {
	Total   *int32                   `json:"total,omitempty"`
	Entries []map[string]interface{} `json:"entries,omitempty"`
}

// NewAdvertiserRelationshipApiKeys instantiates a new AdvertiserRelationshipApiKeys object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdvertiserRelationshipApiKeys() *AdvertiserRelationshipApiKeys {
	this := AdvertiserRelationshipApiKeys{}
	return &this
}

// NewAdvertiserRelationshipApiKeysWithDefaults instantiates a new AdvertiserRelationshipApiKeys object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdvertiserRelationshipApiKeysWithDefaults() *AdvertiserRelationshipApiKeys {
	this := AdvertiserRelationshipApiKeys{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *AdvertiserRelationshipApiKeys) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvertiserRelationshipApiKeys) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *AdvertiserRelationshipApiKeys) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *AdvertiserRelationshipApiKeys) SetTotal(v int32) {
	o.Total = &v
}

// GetEntries returns the Entries field value if set, zero value otherwise.
func (o *AdvertiserRelationshipApiKeys) GetEntries() []map[string]interface{} {
	if o == nil || IsNil(o.Entries) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvertiserRelationshipApiKeys) GetEntriesOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Entries) {
		return nil, false
	}
	return o.Entries, true
}

// HasEntries returns a boolean if a field has been set.
func (o *AdvertiserRelationshipApiKeys) HasEntries() bool {
	if o != nil && !IsNil(o.Entries) {
		return true
	}

	return false
}

// SetEntries gets a reference to the given []map[string]interface{} and assigns it to the Entries field.
func (o *AdvertiserRelationshipApiKeys) SetEntries(v []map[string]interface{}) {
	o.Entries = v
}

func (o AdvertiserRelationshipApiKeys) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdvertiserRelationshipApiKeys) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.Entries) {
		toSerialize["entries"] = o.Entries
	}
	return toSerialize, nil
}

type NullableAdvertiserRelationshipApiKeys struct {
	value *AdvertiserRelationshipApiKeys
	isSet bool
}

func (v NullableAdvertiserRelationshipApiKeys) Get() *AdvertiserRelationshipApiKeys {
	return v.value
}

func (v *NullableAdvertiserRelationshipApiKeys) Set(val *AdvertiserRelationshipApiKeys) {
	v.value = val
	v.isSet = true
}

func (v NullableAdvertiserRelationshipApiKeys) IsSet() bool {
	return v.isSet
}

func (v *NullableAdvertiserRelationshipApiKeys) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdvertiserRelationshipApiKeys(val *AdvertiserRelationshipApiKeys) *NullableAdvertiserRelationshipApiKeys {
	return &NullableAdvertiserRelationshipApiKeys{value: val, isSet: true}
}

func (v NullableAdvertiserRelationshipApiKeys) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdvertiserRelationshipApiKeys) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
