/*
Everflow Network API - Advertisers

API for managing advertisers in the Everflow platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package advertiser

import (
	"encoding/json"
)

// checks if the AdvertiserRelationship type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdvertiserRelationship{}

// AdvertiserRelationship Related data based on requested relationships
type AdvertiserRelationship struct {
	Labels          *AdvertiserRelationshipLabels  `json:"labels,omitempty"`
	AccountManager  *Employee                      `json:"account_manager,omitempty"`
	SalesManager    *Employee                      `json:"sales_manager,omitempty"`
	Reporting       *ReportingData                 `json:"reporting,omitempty"`
	ApiKeys         *AdvertiserRelationshipApiKeys `json:"api_keys,omitempty"`
	ApiWhitelistIps *AdvertiserRelationshipApiKeys `json:"api_whitelist_ips,omitempty"`
	Billing         *Billing                       `json:"billing,omitempty"`
	Settings        *Settings                      `json:"settings,omitempty"`
}

// NewAdvertiserRelationship instantiates a new AdvertiserRelationship object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdvertiserRelationship() *AdvertiserRelationship {
	this := AdvertiserRelationship{}
	return &this
}

// NewAdvertiserRelationshipWithDefaults instantiates a new AdvertiserRelationship object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdvertiserRelationshipWithDefaults() *AdvertiserRelationship {
	this := AdvertiserRelationship{}
	return &this
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *AdvertiserRelationship) GetLabels() AdvertiserRelationshipLabels {
	if o == nil || IsNil(o.Labels) {
		var ret AdvertiserRelationshipLabels
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvertiserRelationship) GetLabelsOk() (*AdvertiserRelationshipLabels, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *AdvertiserRelationship) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given AdvertiserRelationshipLabels and assigns it to the Labels field.
func (o *AdvertiserRelationship) SetLabels(v AdvertiserRelationshipLabels) {
	o.Labels = &v
}

// GetAccountManager returns the AccountManager field value if set, zero value otherwise.
func (o *AdvertiserRelationship) GetAccountManager() Employee {
	if o == nil || IsNil(o.AccountManager) {
		var ret Employee
		return ret
	}
	return *o.AccountManager
}

// GetAccountManagerOk returns a tuple with the AccountManager field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvertiserRelationship) GetAccountManagerOk() (*Employee, bool) {
	if o == nil || IsNil(o.AccountManager) {
		return nil, false
	}
	return o.AccountManager, true
}

// HasAccountManager returns a boolean if a field has been set.
func (o *AdvertiserRelationship) HasAccountManager() bool {
	if o != nil && !IsNil(o.AccountManager) {
		return true
	}

	return false
}

// SetAccountManager gets a reference to the given Employee and assigns it to the AccountManager field.
func (o *AdvertiserRelationship) SetAccountManager(v Employee) {
	o.AccountManager = &v
}

// GetSalesManager returns the SalesManager field value if set, zero value otherwise.
func (o *AdvertiserRelationship) GetSalesManager() Employee {
	if o == nil || IsNil(o.SalesManager) {
		var ret Employee
		return ret
	}
	return *o.SalesManager
}

// GetSalesManagerOk returns a tuple with the SalesManager field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvertiserRelationship) GetSalesManagerOk() (*Employee, bool) {
	if o == nil || IsNil(o.SalesManager) {
		return nil, false
	}
	return o.SalesManager, true
}

// HasSalesManager returns a boolean if a field has been set.
func (o *AdvertiserRelationship) HasSalesManager() bool {
	if o != nil && !IsNil(o.SalesManager) {
		return true
	}

	return false
}

// SetSalesManager gets a reference to the given Employee and assigns it to the SalesManager field.
func (o *AdvertiserRelationship) SetSalesManager(v Employee) {
	o.SalesManager = &v
}

// GetReporting returns the Reporting field value if set, zero value otherwise.
func (o *AdvertiserRelationship) GetReporting() ReportingData {
	if o == nil || IsNil(o.Reporting) {
		var ret ReportingData
		return ret
	}
	return *o.Reporting
}

// GetReportingOk returns a tuple with the Reporting field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvertiserRelationship) GetReportingOk() (*ReportingData, bool) {
	if o == nil || IsNil(o.Reporting) {
		return nil, false
	}
	return o.Reporting, true
}

// HasReporting returns a boolean if a field has been set.
func (o *AdvertiserRelationship) HasReporting() bool {
	if o != nil && !IsNil(o.Reporting) {
		return true
	}

	return false
}

// SetReporting gets a reference to the given ReportingData and assigns it to the Reporting field.
func (o *AdvertiserRelationship) SetReporting(v ReportingData) {
	o.Reporting = &v
}

// GetApiKeys returns the ApiKeys field value if set, zero value otherwise.
func (o *AdvertiserRelationship) GetApiKeys() AdvertiserRelationshipApiKeys {
	if o == nil || IsNil(o.ApiKeys) {
		var ret AdvertiserRelationshipApiKeys
		return ret
	}
	return *o.ApiKeys
}

// GetApiKeysOk returns a tuple with the ApiKeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvertiserRelationship) GetApiKeysOk() (*AdvertiserRelationshipApiKeys, bool) {
	if o == nil || IsNil(o.ApiKeys) {
		return nil, false
	}
	return o.ApiKeys, true
}

// HasApiKeys returns a boolean if a field has been set.
func (o *AdvertiserRelationship) HasApiKeys() bool {
	if o != nil && !IsNil(o.ApiKeys) {
		return true
	}

	return false
}

// SetApiKeys gets a reference to the given AdvertiserRelationshipApiKeys and assigns it to the ApiKeys field.
func (o *AdvertiserRelationship) SetApiKeys(v AdvertiserRelationshipApiKeys) {
	o.ApiKeys = &v
}

// GetApiWhitelistIps returns the ApiWhitelistIps field value if set, zero value otherwise.
func (o *AdvertiserRelationship) GetApiWhitelistIps() AdvertiserRelationshipApiKeys {
	if o == nil || IsNil(o.ApiWhitelistIps) {
		var ret AdvertiserRelationshipApiKeys
		return ret
	}
	return *o.ApiWhitelistIps
}

// GetApiWhitelistIpsOk returns a tuple with the ApiWhitelistIps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvertiserRelationship) GetApiWhitelistIpsOk() (*AdvertiserRelationshipApiKeys, bool) {
	if o == nil || IsNil(o.ApiWhitelistIps) {
		return nil, false
	}
	return o.ApiWhitelistIps, true
}

// HasApiWhitelistIps returns a boolean if a field has been set.
func (o *AdvertiserRelationship) HasApiWhitelistIps() bool {
	if o != nil && !IsNil(o.ApiWhitelistIps) {
		return true
	}

	return false
}

// SetApiWhitelistIps gets a reference to the given AdvertiserRelationshipApiKeys and assigns it to the ApiWhitelistIps field.
func (o *AdvertiserRelationship) SetApiWhitelistIps(v AdvertiserRelationshipApiKeys) {
	o.ApiWhitelistIps = &v
}

// GetBilling returns the Billing field value if set, zero value otherwise.
func (o *AdvertiserRelationship) GetBilling() Billing {
	if o == nil || IsNil(o.Billing) {
		var ret Billing
		return ret
	}
	return *o.Billing
}

// GetBillingOk returns a tuple with the Billing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvertiserRelationship) GetBillingOk() (*Billing, bool) {
	if o == nil || IsNil(o.Billing) {
		return nil, false
	}
	return o.Billing, true
}

// HasBilling returns a boolean if a field has been set.
func (o *AdvertiserRelationship) HasBilling() bool {
	if o != nil && !IsNil(o.Billing) {
		return true
	}

	return false
}

// SetBilling gets a reference to the given Billing and assigns it to the Billing field.
func (o *AdvertiserRelationship) SetBilling(v Billing) {
	o.Billing = &v
}

// GetSettings returns the Settings field value if set, zero value otherwise.
func (o *AdvertiserRelationship) GetSettings() Settings {
	if o == nil || IsNil(o.Settings) {
		var ret Settings
		return ret
	}
	return *o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AdvertiserRelationship) GetSettingsOk() (*Settings, bool) {
	if o == nil || IsNil(o.Settings) {
		return nil, false
	}
	return o.Settings, true
}

// HasSettings returns a boolean if a field has been set.
func (o *AdvertiserRelationship) HasSettings() bool {
	if o != nil && !IsNil(o.Settings) {
		return true
	}

	return false
}

// SetSettings gets a reference to the given Settings and assigns it to the Settings field.
func (o *AdvertiserRelationship) SetSettings(v Settings) {
	o.Settings = &v
}

func (o AdvertiserRelationship) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdvertiserRelationship) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.AccountManager) {
		toSerialize["account_manager"] = o.AccountManager
	}
	if !IsNil(o.SalesManager) {
		toSerialize["sales_manager"] = o.SalesManager
	}
	if !IsNil(o.Reporting) {
		toSerialize["reporting"] = o.Reporting
	}
	if !IsNil(o.ApiKeys) {
		toSerialize["api_keys"] = o.ApiKeys
	}
	if !IsNil(o.ApiWhitelistIps) {
		toSerialize["api_whitelist_ips"] = o.ApiWhitelistIps
	}
	if !IsNil(o.Billing) {
		toSerialize["billing"] = o.Billing
	}
	if !IsNil(o.Settings) {
		toSerialize["settings"] = o.Settings
	}
	return toSerialize, nil
}

type NullableAdvertiserRelationship struct {
	value *AdvertiserRelationship
	isSet bool
}

func (v NullableAdvertiserRelationship) Get() *AdvertiserRelationship {
	return v.value
}

func (v *NullableAdvertiserRelationship) Set(val *AdvertiserRelationship) {
	v.value = val
	v.isSet = true
}

func (v NullableAdvertiserRelationship) IsSet() bool {
	return v.isSet
}

func (v *NullableAdvertiserRelationship) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdvertiserRelationship(val *AdvertiserRelationship) *NullableAdvertiserRelationship {
	return &NullableAdvertiserRelationship{value: val, isSet: true}
}

func (v NullableAdvertiserRelationship) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdvertiserRelationship) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
