/*
Everflow Network API - Advertisers

API for managing advertisers in the Everflow platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package advertiser

import (
	"encoding/json"
)

// checks if the Advertiser type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Advertiser{}

// Advertiser struct for Advertiser
type Advertiser struct {
	// The unique ID of the advertiser
	NetworkAdvertiserId *int32 `json:"network_advertiser_id,omitempty"`
	// The network ID
	NetworkId *int32 `json:"network_id,omitempty"`
	// The name of the advertiser
	Name *string `json:"name,omitempty"`
	// Status of the advertiser
	AccountStatus *string `json:"account_status,omitempty"`
	// The employee id of the advertiser's account manager
	NetworkEmployeeId *int32 `json:"network_employee_id,omitempty"`
	// Internal notes for the advertiser
	InternalNotes *string `json:"internal_notes,omitempty"`
	// The address id of the advertiser
	AddressId *int32 `json:"address_id,omitempty"`
	// Whether contact address is enabled
	IsContactAddressEnabled *bool `json:"is_contact_address_enabled,omitempty"`
	// The employee id of the advertiser's sales manager
	SalesManagerId *int32 `json:"sales_manager_id,omitempty"`
	// Whether to expose publisher reporting data
	IsExposePublisherReportingData NullableBool `json:"is_expose_publisher_reporting_data,omitempty"`
	// The advertiser's default currency
	DefaultCurrencyId *string `json:"default_currency_id,omitempty"`
	// The name of the shopping cart or attribution platform
	PlatformName *string `json:"platform_name,omitempty"`
	// The URL for logging into the advertiser's platform
	PlatformUrl *string `json:"platform_url,omitempty"`
	// The username for logging into the advertiser's platform
	PlatformUsername *string `json:"platform_username,omitempty"`
	// The timezone used in the advertiser's platform reporting
	ReportingTimezoneId *int32 `json:"reporting_timezone_id,omitempty"`
	// The email address of the accounting contact
	AccountingContactEmail *string `json:"accounting_contact_email,omitempty"`
	// Verification token for incoming postbacks
	VerificationToken *string `json:"verification_token,omitempty"`
	// The string used for the offer id macro
	OfferIdMacro *string `json:"offer_id_macro,omitempty"`
	// The string used for the affiliate id macro
	AffiliateIdMacro *string `json:"affiliate_id_macro,omitempty"`
	// How attribution works for this advertiser
	AttributionMethod *string `json:"attribution_method,omitempty"`
	// How email attribution works for this advertiser
	EmailAttributionMethod *string `json:"email_attribution_method,omitempty"`
	// Attribution priority between click and coupon code
	AttributionPriority *string `json:"attribution_priority,omitempty"`
	// Creation timestamp
	TimeCreated *int32 `json:"time_created,omitempty"`
	// Last save timestamp
	TimeSaved *int32 `json:"time_saved,omitempty"`
	Relationship *AdvertiserRelationship `json:"relationship,omitempty"`
}

// NewAdvertiser instantiates a new Advertiser object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdvertiser() *Advertiser {
	this := Advertiser{}
	return &this
}

// NewAdvertiserWithDefaults instantiates a new Advertiser object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdvertiserWithDefaults() *Advertiser {
	this := Advertiser{}
	return &this
}

// GetNetworkAdvertiserId returns the NetworkAdvertiserId field value if set, zero value otherwise.
func (o *Advertiser) GetNetworkAdvertiserId() int32 {
	if o == nil || IsNil(o.NetworkAdvertiserId) {
		var ret int32
		return ret
	}
	return *o.NetworkAdvertiserId
}

// GetNetworkAdvertiserIdOk returns a tuple with the NetworkAdvertiserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Advertiser) GetNetworkAdvertiserIdOk() (*int32, bool) {
	if o == nil || IsNil(o.NetworkAdvertiserId) {
		return nil, false
	}
	return o.NetworkAdvertiserId, true
}

// HasNetworkAdvertiserId returns a boolean if a field has been set.
func (o *Advertiser) HasNetworkAdvertiserId() bool {
	if o != nil && !IsNil(o.NetworkAdvertiserId) {
		return true
	}

	return false
}

// SetNetworkAdvertiserId gets a reference to the given int32 and assigns it to the NetworkAdvertiserId field.
func (o *Advertiser) SetNetworkAdvertiserId(v int32) {
	o.NetworkAdvertiserId = &v
}

// GetNetworkId returns the NetworkId field value if set, zero value otherwise.
func (o *Advertiser) GetNetworkId() int32 {
	if o == nil || IsNil(o.NetworkId) {
		var ret int32
		return ret
	}
	return *o.NetworkId
}

// GetNetworkIdOk returns a tuple with the NetworkId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Advertiser) GetNetworkIdOk() (*int32, bool) {
	if o == nil || IsNil(o.NetworkId) {
		return nil, false
	}
	return o.NetworkId, true
}

// HasNetworkId returns a boolean if a field has been set.
func (o *Advertiser) HasNetworkId() bool {
	if o != nil && !IsNil(o.NetworkId) {
		return true
	}

	return false
}

// SetNetworkId gets a reference to the given int32 and assigns it to the NetworkId field.
func (o *Advertiser) SetNetworkId(v int32) {
	o.NetworkId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Advertiser) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Advertiser) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Advertiser) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Advertiser) SetName(v string) {
	o.Name = &v
}

// GetAccountStatus returns the AccountStatus field value if set, zero value otherwise.
func (o *Advertiser) GetAccountStatus() string {
	if o == nil || IsNil(o.AccountStatus) {
		var ret string
		return ret
	}
	return *o.AccountStatus
}

// GetAccountStatusOk returns a tuple with the AccountStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Advertiser) GetAccountStatusOk() (*string, bool) {
	if o == nil || IsNil(o.AccountStatus) {
		return nil, false
	}
	return o.AccountStatus, true
}

// HasAccountStatus returns a boolean if a field has been set.
func (o *Advertiser) HasAccountStatus() bool {
	if o != nil && !IsNil(o.AccountStatus) {
		return true
	}

	return false
}

// SetAccountStatus gets a reference to the given string and assigns it to the AccountStatus field.
func (o *Advertiser) SetAccountStatus(v string) {
	o.AccountStatus = &v
}

// GetNetworkEmployeeId returns the NetworkEmployeeId field value if set, zero value otherwise.
func (o *Advertiser) GetNetworkEmployeeId() int32 {
	if o == nil || IsNil(o.NetworkEmployeeId) {
		var ret int32
		return ret
	}
	return *o.NetworkEmployeeId
}

// GetNetworkEmployeeIdOk returns a tuple with the NetworkEmployeeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Advertiser) GetNetworkEmployeeIdOk() (*int32, bool) {
	if o == nil || IsNil(o.NetworkEmployeeId) {
		return nil, false
	}
	return o.NetworkEmployeeId, true
}

// HasNetworkEmployeeId returns a boolean if a field has been set.
func (o *Advertiser) HasNetworkEmployeeId() bool {
	if o != nil && !IsNil(o.NetworkEmployeeId) {
		return true
	}

	return false
}

// SetNetworkEmployeeId gets a reference to the given int32 and assigns it to the NetworkEmployeeId field.
func (o *Advertiser) SetNetworkEmployeeId(v int32) {
	o.NetworkEmployeeId = &v
}

// GetInternalNotes returns the InternalNotes field value if set, zero value otherwise.
func (o *Advertiser) GetInternalNotes() string {
	if o == nil || IsNil(o.InternalNotes) {
		var ret string
		return ret
	}
	return *o.InternalNotes
}

// GetInternalNotesOk returns a tuple with the InternalNotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Advertiser) GetInternalNotesOk() (*string, bool) {
	if o == nil || IsNil(o.InternalNotes) {
		return nil, false
	}
	return o.InternalNotes, true
}

// HasInternalNotes returns a boolean if a field has been set.
func (o *Advertiser) HasInternalNotes() bool {
	if o != nil && !IsNil(o.InternalNotes) {
		return true
	}

	return false
}

// SetInternalNotes gets a reference to the given string and assigns it to the InternalNotes field.
func (o *Advertiser) SetInternalNotes(v string) {
	o.InternalNotes = &v
}

// GetAddressId returns the AddressId field value if set, zero value otherwise.
func (o *Advertiser) GetAddressId() int32 {
	if o == nil || IsNil(o.AddressId) {
		var ret int32
		return ret
	}
	return *o.AddressId
}

// GetAddressIdOk returns a tuple with the AddressId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Advertiser) GetAddressIdOk() (*int32, bool) {
	if o == nil || IsNil(o.AddressId) {
		return nil, false
	}
	return o.AddressId, true
}

// HasAddressId returns a boolean if a field has been set.
func (o *Advertiser) HasAddressId() bool {
	if o != nil && !IsNil(o.AddressId) {
		return true
	}

	return false
}

// SetAddressId gets a reference to the given int32 and assigns it to the AddressId field.
func (o *Advertiser) SetAddressId(v int32) {
	o.AddressId = &v
}

// GetIsContactAddressEnabled returns the IsContactAddressEnabled field value if set, zero value otherwise.
func (o *Advertiser) GetIsContactAddressEnabled() bool {
	if o == nil || IsNil(o.IsContactAddressEnabled) {
		var ret bool
		return ret
	}
	return *o.IsContactAddressEnabled
}

// GetIsContactAddressEnabledOk returns a tuple with the IsContactAddressEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Advertiser) GetIsContactAddressEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsContactAddressEnabled) {
		return nil, false
	}
	return o.IsContactAddressEnabled, true
}

// HasIsContactAddressEnabled returns a boolean if a field has been set.
func (o *Advertiser) HasIsContactAddressEnabled() bool {
	if o != nil && !IsNil(o.IsContactAddressEnabled) {
		return true
	}

	return false
}

// SetIsContactAddressEnabled gets a reference to the given bool and assigns it to the IsContactAddressEnabled field.
func (o *Advertiser) SetIsContactAddressEnabled(v bool) {
	o.IsContactAddressEnabled = &v
}

// GetSalesManagerId returns the SalesManagerId field value if set, zero value otherwise.
func (o *Advertiser) GetSalesManagerId() int32 {
	if o == nil || IsNil(o.SalesManagerId) {
		var ret int32
		return ret
	}
	return *o.SalesManagerId
}

// GetSalesManagerIdOk returns a tuple with the SalesManagerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Advertiser) GetSalesManagerIdOk() (*int32, bool) {
	if o == nil || IsNil(o.SalesManagerId) {
		return nil, false
	}
	return o.SalesManagerId, true
}

// HasSalesManagerId returns a boolean if a field has been set.
func (o *Advertiser) HasSalesManagerId() bool {
	if o != nil && !IsNil(o.SalesManagerId) {
		return true
	}

	return false
}

// SetSalesManagerId gets a reference to the given int32 and assigns it to the SalesManagerId field.
func (o *Advertiser) SetSalesManagerId(v int32) {
	o.SalesManagerId = &v
}

// GetIsExposePublisherReportingData returns the IsExposePublisherReportingData field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Advertiser) GetIsExposePublisherReportingData() bool {
	if o == nil || IsNil(o.IsExposePublisherReportingData.Get()) {
		var ret bool
		return ret
	}
	return *o.IsExposePublisherReportingData.Get()
}

// GetIsExposePublisherReportingDataOk returns a tuple with the IsExposePublisherReportingData field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Advertiser) GetIsExposePublisherReportingDataOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsExposePublisherReportingData.Get(), o.IsExposePublisherReportingData.IsSet()
}

// HasIsExposePublisherReportingData returns a boolean if a field has been set.
func (o *Advertiser) HasIsExposePublisherReportingData() bool {
	if o != nil && o.IsExposePublisherReportingData.IsSet() {
		return true
	}

	return false
}

// SetIsExposePublisherReportingData gets a reference to the given NullableBool and assigns it to the IsExposePublisherReportingData field.
func (o *Advertiser) SetIsExposePublisherReportingData(v bool) {
	o.IsExposePublisherReportingData.Set(&v)
}
// SetIsExposePublisherReportingDataNil sets the value for IsExposePublisherReportingData to be an explicit nil
func (o *Advertiser) SetIsExposePublisherReportingDataNil() {
	o.IsExposePublisherReportingData.Set(nil)
}

// UnsetIsExposePublisherReportingData ensures that no value is present for IsExposePublisherReportingData, not even an explicit nil
func (o *Advertiser) UnsetIsExposePublisherReportingData() {
	o.IsExposePublisherReportingData.Unset()
}

// GetDefaultCurrencyId returns the DefaultCurrencyId field value if set, zero value otherwise.
func (o *Advertiser) GetDefaultCurrencyId() string {
	if o == nil || IsNil(o.DefaultCurrencyId) {
		var ret string
		return ret
	}
	return *o.DefaultCurrencyId
}

// GetDefaultCurrencyIdOk returns a tuple with the DefaultCurrencyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Advertiser) GetDefaultCurrencyIdOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultCurrencyId) {
		return nil, false
	}
	return o.DefaultCurrencyId, true
}

// HasDefaultCurrencyId returns a boolean if a field has been set.
func (o *Advertiser) HasDefaultCurrencyId() bool {
	if o != nil && !IsNil(o.DefaultCurrencyId) {
		return true
	}

	return false
}

// SetDefaultCurrencyId gets a reference to the given string and assigns it to the DefaultCurrencyId field.
func (o *Advertiser) SetDefaultCurrencyId(v string) {
	o.DefaultCurrencyId = &v
}

// GetPlatformName returns the PlatformName field value if set, zero value otherwise.
func (o *Advertiser) GetPlatformName() string {
	if o == nil || IsNil(o.PlatformName) {
		var ret string
		return ret
	}
	return *o.PlatformName
}

// GetPlatformNameOk returns a tuple with the PlatformName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Advertiser) GetPlatformNameOk() (*string, bool) {
	if o == nil || IsNil(o.PlatformName) {
		return nil, false
	}
	return o.PlatformName, true
}

// HasPlatformName returns a boolean if a field has been set.
func (o *Advertiser) HasPlatformName() bool {
	if o != nil && !IsNil(o.PlatformName) {
		return true
	}

	return false
}

// SetPlatformName gets a reference to the given string and assigns it to the PlatformName field.
func (o *Advertiser) SetPlatformName(v string) {
	o.PlatformName = &v
}

// GetPlatformUrl returns the PlatformUrl field value if set, zero value otherwise.
func (o *Advertiser) GetPlatformUrl() string {
	if o == nil || IsNil(o.PlatformUrl) {
		var ret string
		return ret
	}
	return *o.PlatformUrl
}

// GetPlatformUrlOk returns a tuple with the PlatformUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Advertiser) GetPlatformUrlOk() (*string, bool) {
	if o == nil || IsNil(o.PlatformUrl) {
		return nil, false
	}
	return o.PlatformUrl, true
}

// HasPlatformUrl returns a boolean if a field has been set.
func (o *Advertiser) HasPlatformUrl() bool {
	if o != nil && !IsNil(o.PlatformUrl) {
		return true
	}

	return false
}

// SetPlatformUrl gets a reference to the given string and assigns it to the PlatformUrl field.
func (o *Advertiser) SetPlatformUrl(v string) {
	o.PlatformUrl = &v
}

// GetPlatformUsername returns the PlatformUsername field value if set, zero value otherwise.
func (o *Advertiser) GetPlatformUsername() string {
	if o == nil || IsNil(o.PlatformUsername) {
		var ret string
		return ret
	}
	return *o.PlatformUsername
}

// GetPlatformUsernameOk returns a tuple with the PlatformUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Advertiser) GetPlatformUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.PlatformUsername) {
		return nil, false
	}
	return o.PlatformUsername, true
}

// HasPlatformUsername returns a boolean if a field has been set.
func (o *Advertiser) HasPlatformUsername() bool {
	if o != nil && !IsNil(o.PlatformUsername) {
		return true
	}

	return false
}

// SetPlatformUsername gets a reference to the given string and assigns it to the PlatformUsername field.
func (o *Advertiser) SetPlatformUsername(v string) {
	o.PlatformUsername = &v
}

// GetReportingTimezoneId returns the ReportingTimezoneId field value if set, zero value otherwise.
func (o *Advertiser) GetReportingTimezoneId() int32 {
	if o == nil || IsNil(o.ReportingTimezoneId) {
		var ret int32
		return ret
	}
	return *o.ReportingTimezoneId
}

// GetReportingTimezoneIdOk returns a tuple with the ReportingTimezoneId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Advertiser) GetReportingTimezoneIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ReportingTimezoneId) {
		return nil, false
	}
	return o.ReportingTimezoneId, true
}

// HasReportingTimezoneId returns a boolean if a field has been set.
func (o *Advertiser) HasReportingTimezoneId() bool {
	if o != nil && !IsNil(o.ReportingTimezoneId) {
		return true
	}

	return false
}

// SetReportingTimezoneId gets a reference to the given int32 and assigns it to the ReportingTimezoneId field.
func (o *Advertiser) SetReportingTimezoneId(v int32) {
	o.ReportingTimezoneId = &v
}

// GetAccountingContactEmail returns the AccountingContactEmail field value if set, zero value otherwise.
func (o *Advertiser) GetAccountingContactEmail() string {
	if o == nil || IsNil(o.AccountingContactEmail) {
		var ret string
		return ret
	}
	return *o.AccountingContactEmail
}

// GetAccountingContactEmailOk returns a tuple with the AccountingContactEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Advertiser) GetAccountingContactEmailOk() (*string, bool) {
	if o == nil || IsNil(o.AccountingContactEmail) {
		return nil, false
	}
	return o.AccountingContactEmail, true
}

// HasAccountingContactEmail returns a boolean if a field has been set.
func (o *Advertiser) HasAccountingContactEmail() bool {
	if o != nil && !IsNil(o.AccountingContactEmail) {
		return true
	}

	return false
}

// SetAccountingContactEmail gets a reference to the given string and assigns it to the AccountingContactEmail field.
func (o *Advertiser) SetAccountingContactEmail(v string) {
	o.AccountingContactEmail = &v
}

// GetVerificationToken returns the VerificationToken field value if set, zero value otherwise.
func (o *Advertiser) GetVerificationToken() string {
	if o == nil || IsNil(o.VerificationToken) {
		var ret string
		return ret
	}
	return *o.VerificationToken
}

// GetVerificationTokenOk returns a tuple with the VerificationToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Advertiser) GetVerificationTokenOk() (*string, bool) {
	if o == nil || IsNil(o.VerificationToken) {
		return nil, false
	}
	return o.VerificationToken, true
}

// HasVerificationToken returns a boolean if a field has been set.
func (o *Advertiser) HasVerificationToken() bool {
	if o != nil && !IsNil(o.VerificationToken) {
		return true
	}

	return false
}

// SetVerificationToken gets a reference to the given string and assigns it to the VerificationToken field.
func (o *Advertiser) SetVerificationToken(v string) {
	o.VerificationToken = &v
}

// GetOfferIdMacro returns the OfferIdMacro field value if set, zero value otherwise.
func (o *Advertiser) GetOfferIdMacro() string {
	if o == nil || IsNil(o.OfferIdMacro) {
		var ret string
		return ret
	}
	return *o.OfferIdMacro
}

// GetOfferIdMacroOk returns a tuple with the OfferIdMacro field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Advertiser) GetOfferIdMacroOk() (*string, bool) {
	if o == nil || IsNil(o.OfferIdMacro) {
		return nil, false
	}
	return o.OfferIdMacro, true
}

// HasOfferIdMacro returns a boolean if a field has been set.
func (o *Advertiser) HasOfferIdMacro() bool {
	if o != nil && !IsNil(o.OfferIdMacro) {
		return true
	}

	return false
}

// SetOfferIdMacro gets a reference to the given string and assigns it to the OfferIdMacro field.
func (o *Advertiser) SetOfferIdMacro(v string) {
	o.OfferIdMacro = &v
}

// GetAffiliateIdMacro returns the AffiliateIdMacro field value if set, zero value otherwise.
func (o *Advertiser) GetAffiliateIdMacro() string {
	if o == nil || IsNil(o.AffiliateIdMacro) {
		var ret string
		return ret
	}
	return *o.AffiliateIdMacro
}

// GetAffiliateIdMacroOk returns a tuple with the AffiliateIdMacro field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Advertiser) GetAffiliateIdMacroOk() (*string, bool) {
	if o == nil || IsNil(o.AffiliateIdMacro) {
		return nil, false
	}
	return o.AffiliateIdMacro, true
}

// HasAffiliateIdMacro returns a boolean if a field has been set.
func (o *Advertiser) HasAffiliateIdMacro() bool {
	if o != nil && !IsNil(o.AffiliateIdMacro) {
		return true
	}

	return false
}

// SetAffiliateIdMacro gets a reference to the given string and assigns it to the AffiliateIdMacro field.
func (o *Advertiser) SetAffiliateIdMacro(v string) {
	o.AffiliateIdMacro = &v
}

// GetAttributionMethod returns the AttributionMethod field value if set, zero value otherwise.
func (o *Advertiser) GetAttributionMethod() string {
	if o == nil || IsNil(o.AttributionMethod) {
		var ret string
		return ret
	}
	return *o.AttributionMethod
}

// GetAttributionMethodOk returns a tuple with the AttributionMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Advertiser) GetAttributionMethodOk() (*string, bool) {
	if o == nil || IsNil(o.AttributionMethod) {
		return nil, false
	}
	return o.AttributionMethod, true
}

// HasAttributionMethod returns a boolean if a field has been set.
func (o *Advertiser) HasAttributionMethod() bool {
	if o != nil && !IsNil(o.AttributionMethod) {
		return true
	}

	return false
}

// SetAttributionMethod gets a reference to the given string and assigns it to the AttributionMethod field.
func (o *Advertiser) SetAttributionMethod(v string) {
	o.AttributionMethod = &v
}

// GetEmailAttributionMethod returns the EmailAttributionMethod field value if set, zero value otherwise.
func (o *Advertiser) GetEmailAttributionMethod() string {
	if o == nil || IsNil(o.EmailAttributionMethod) {
		var ret string
		return ret
	}
	return *o.EmailAttributionMethod
}

// GetEmailAttributionMethodOk returns a tuple with the EmailAttributionMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Advertiser) GetEmailAttributionMethodOk() (*string, bool) {
	if o == nil || IsNil(o.EmailAttributionMethod) {
		return nil, false
	}
	return o.EmailAttributionMethod, true
}

// HasEmailAttributionMethod returns a boolean if a field has been set.
func (o *Advertiser) HasEmailAttributionMethod() bool {
	if o != nil && !IsNil(o.EmailAttributionMethod) {
		return true
	}

	return false
}

// SetEmailAttributionMethod gets a reference to the given string and assigns it to the EmailAttributionMethod field.
func (o *Advertiser) SetEmailAttributionMethod(v string) {
	o.EmailAttributionMethod = &v
}

// GetAttributionPriority returns the AttributionPriority field value if set, zero value otherwise.
func (o *Advertiser) GetAttributionPriority() string {
	if o == nil || IsNil(o.AttributionPriority) {
		var ret string
		return ret
	}
	return *o.AttributionPriority
}

// GetAttributionPriorityOk returns a tuple with the AttributionPriority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Advertiser) GetAttributionPriorityOk() (*string, bool) {
	if o == nil || IsNil(o.AttributionPriority) {
		return nil, false
	}
	return o.AttributionPriority, true
}

// HasAttributionPriority returns a boolean if a field has been set.
func (o *Advertiser) HasAttributionPriority() bool {
	if o != nil && !IsNil(o.AttributionPriority) {
		return true
	}

	return false
}

// SetAttributionPriority gets a reference to the given string and assigns it to the AttributionPriority field.
func (o *Advertiser) SetAttributionPriority(v string) {
	o.AttributionPriority = &v
}

// GetTimeCreated returns the TimeCreated field value if set, zero value otherwise.
func (o *Advertiser) GetTimeCreated() int32 {
	if o == nil || IsNil(o.TimeCreated) {
		var ret int32
		return ret
	}
	return *o.TimeCreated
}

// GetTimeCreatedOk returns a tuple with the TimeCreated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Advertiser) GetTimeCreatedOk() (*int32, bool) {
	if o == nil || IsNil(o.TimeCreated) {
		return nil, false
	}
	return o.TimeCreated, true
}

// HasTimeCreated returns a boolean if a field has been set.
func (o *Advertiser) HasTimeCreated() bool {
	if o != nil && !IsNil(o.TimeCreated) {
		return true
	}

	return false
}

// SetTimeCreated gets a reference to the given int32 and assigns it to the TimeCreated field.
func (o *Advertiser) SetTimeCreated(v int32) {
	o.TimeCreated = &v
}

// GetTimeSaved returns the TimeSaved field value if set, zero value otherwise.
func (o *Advertiser) GetTimeSaved() int32 {
	if o == nil || IsNil(o.TimeSaved) {
		var ret int32
		return ret
	}
	return *o.TimeSaved
}

// GetTimeSavedOk returns a tuple with the TimeSaved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Advertiser) GetTimeSavedOk() (*int32, bool) {
	if o == nil || IsNil(o.TimeSaved) {
		return nil, false
	}
	return o.TimeSaved, true
}

// HasTimeSaved returns a boolean if a field has been set.
func (o *Advertiser) HasTimeSaved() bool {
	if o != nil && !IsNil(o.TimeSaved) {
		return true
	}

	return false
}

// SetTimeSaved gets a reference to the given int32 and assigns it to the TimeSaved field.
func (o *Advertiser) SetTimeSaved(v int32) {
	o.TimeSaved = &v
}

// GetRelationship returns the Relationship field value if set, zero value otherwise.
func (o *Advertiser) GetRelationship() AdvertiserRelationship {
	if o == nil || IsNil(o.Relationship) {
		var ret AdvertiserRelationship
		return ret
	}
	return *o.Relationship
}

// GetRelationshipOk returns a tuple with the Relationship field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Advertiser) GetRelationshipOk() (*AdvertiserRelationship, bool) {
	if o == nil || IsNil(o.Relationship) {
		return nil, false
	}
	return o.Relationship, true
}

// HasRelationship returns a boolean if a field has been set.
func (o *Advertiser) HasRelationship() bool {
	if o != nil && !IsNil(o.Relationship) {
		return true
	}

	return false
}

// SetRelationship gets a reference to the given AdvertiserRelationship and assigns it to the Relationship field.
func (o *Advertiser) SetRelationship(v AdvertiserRelationship) {
	o.Relationship = &v
}

func (o Advertiser) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Advertiser) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NetworkAdvertiserId) {
		toSerialize["network_advertiser_id"] = o.NetworkAdvertiserId
	}
	if !IsNil(o.NetworkId) {
		toSerialize["network_id"] = o.NetworkId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.AccountStatus) {
		toSerialize["account_status"] = o.AccountStatus
	}
	if !IsNil(o.NetworkEmployeeId) {
		toSerialize["network_employee_id"] = o.NetworkEmployeeId
	}
	if !IsNil(o.InternalNotes) {
		toSerialize["internal_notes"] = o.InternalNotes
	}
	if !IsNil(o.AddressId) {
		toSerialize["address_id"] = o.AddressId
	}
	if !IsNil(o.IsContactAddressEnabled) {
		toSerialize["is_contact_address_enabled"] = o.IsContactAddressEnabled
	}
	if !IsNil(o.SalesManagerId) {
		toSerialize["sales_manager_id"] = o.SalesManagerId
	}
	if o.IsExposePublisherReportingData.IsSet() {
		toSerialize["is_expose_publisher_reporting_data"] = o.IsExposePublisherReportingData.Get()
	}
	if !IsNil(o.DefaultCurrencyId) {
		toSerialize["default_currency_id"] = o.DefaultCurrencyId
	}
	if !IsNil(o.PlatformName) {
		toSerialize["platform_name"] = o.PlatformName
	}
	if !IsNil(o.PlatformUrl) {
		toSerialize["platform_url"] = o.PlatformUrl
	}
	if !IsNil(o.PlatformUsername) {
		toSerialize["platform_username"] = o.PlatformUsername
	}
	if !IsNil(o.ReportingTimezoneId) {
		toSerialize["reporting_timezone_id"] = o.ReportingTimezoneId
	}
	if !IsNil(o.AccountingContactEmail) {
		toSerialize["accounting_contact_email"] = o.AccountingContactEmail
	}
	if !IsNil(o.VerificationToken) {
		toSerialize["verification_token"] = o.VerificationToken
	}
	if !IsNil(o.OfferIdMacro) {
		toSerialize["offer_id_macro"] = o.OfferIdMacro
	}
	if !IsNil(o.AffiliateIdMacro) {
		toSerialize["affiliate_id_macro"] = o.AffiliateIdMacro
	}
	if !IsNil(o.AttributionMethod) {
		toSerialize["attribution_method"] = o.AttributionMethod
	}
	if !IsNil(o.EmailAttributionMethod) {
		toSerialize["email_attribution_method"] = o.EmailAttributionMethod
	}
	if !IsNil(o.AttributionPriority) {
		toSerialize["attribution_priority"] = o.AttributionPriority
	}
	if !IsNil(o.TimeCreated) {
		toSerialize["time_created"] = o.TimeCreated
	}
	if !IsNil(o.TimeSaved) {
		toSerialize["time_saved"] = o.TimeSaved
	}
	if !IsNil(o.Relationship) {
		toSerialize["relationship"] = o.Relationship
	}
	return toSerialize, nil
}

type NullableAdvertiser struct {
	value *Advertiser
	isSet bool
}

func (v NullableAdvertiser) Get() *Advertiser {
	return v.value
}

func (v *NullableAdvertiser) Set(val *Advertiser) {
	v.value = val
	v.isSet = true
}

func (v NullableAdvertiser) IsSet() bool {
	return v.isSet
}

func (v *NullableAdvertiser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdvertiser(val *Advertiser) *NullableAdvertiser {
	return &NullableAdvertiser{value: val, isSet: true}
}

func (v NullableAdvertiser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdvertiser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


