/*
Everflow Network API - Advertisers

API for managing advertisers in the Everflow platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package advertiser

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateAdvertiserRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAdvertiserRequest{}

// CreateAdvertiserRequest struct for CreateAdvertiserRequest
type CreateAdvertiserRequest struct {
	// The name of the advertiser
	Name string `json:"name"`
	// Status of the advertiser
	AccountStatus string `json:"account_status"`
	// The employee id of the advertiser's account manager
	NetworkEmployeeId int32 `json:"network_employee_id"`
	// Internal notes for the advertiser
	InternalNotes *string `json:"internal_notes,omitempty"`
	// The address id of the advertiser
	AddressId *int32 `json:"address_id,omitempty"`
	// Whether or not to include a contact address for this advertiser
	IsContactAddressEnabled *bool `json:"is_contact_address_enabled,omitempty"`
	// The employee id of the advertiser's sales manager
	SalesManagerId *int32 `json:"sales_manager_id,omitempty"`
	// The advertiser's default currency
	DefaultCurrencyId string `json:"default_currency_id"`
	// The name of the shopping cart or attribution platform
	PlatformName *string `json:"platform_name,omitempty"`
	// The URL for logging into the advertiser's platform
	PlatformUrl *string `json:"platform_url,omitempty"`
	// The username for logging into the advertiser's platform
	PlatformUsername *string `json:"platform_username,omitempty"`
	// The timezone used in the advertiser's platform reporting
	ReportingTimezoneId int32 `json:"reporting_timezone_id"`
	// Determines how attribution works for this advertiser
	AttributionMethod string `json:"attribution_method"`
	// Determines how email attribution works for this advertiser
	EmailAttributionMethod string `json:"email_attribution_method"`
	// Determines attribution priority between click and coupon code
	AttributionPriority string `json:"attribution_priority"`
	// The email address of the accounting contact
	AccountingContactEmail *string `json:"accounting_contact_email,omitempty"`
	// Verification token for incoming postbacks
	VerificationToken *string `json:"verification_token,omitempty"`
	// The string used for the offer id macro
	OfferIdMacro *string `json:"offer_id_macro,omitempty"`
	// The string used for the affiliate id macro
	AffiliateIdMacro *string `json:"affiliate_id_macro,omitempty"`
	// The list of labels associated with the advertiser
	Labels []string `json:"labels,omitempty"`
	// List of advertiser users (maximum one)
	Users []AdvertiserUser `json:"users,omitempty"`
	ContactAddress *ContactAddress `json:"contact_address,omitempty"`
	Billing *Billing `json:"billing,omitempty"`
	Settings *Settings `json:"settings,omitempty"`
}

type _CreateAdvertiserRequest CreateAdvertiserRequest

// NewCreateAdvertiserRequest instantiates a new CreateAdvertiserRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAdvertiserRequest(name string, accountStatus string, networkEmployeeId int32, defaultCurrencyId string, reportingTimezoneId int32, attributionMethod string, emailAttributionMethod string, attributionPriority string) *CreateAdvertiserRequest {
	this := CreateAdvertiserRequest{}
	this.Name = name
	this.AccountStatus = accountStatus
	this.NetworkEmployeeId = networkEmployeeId
	var isContactAddressEnabled bool = false
	this.IsContactAddressEnabled = &isContactAddressEnabled
	this.DefaultCurrencyId = defaultCurrencyId
	this.ReportingTimezoneId = reportingTimezoneId
	this.AttributionMethod = attributionMethod
	this.EmailAttributionMethod = emailAttributionMethod
	this.AttributionPriority = attributionPriority
	return &this
}

// NewCreateAdvertiserRequestWithDefaults instantiates a new CreateAdvertiserRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAdvertiserRequestWithDefaults() *CreateAdvertiserRequest {
	this := CreateAdvertiserRequest{}
	var isContactAddressEnabled bool = false
	this.IsContactAddressEnabled = &isContactAddressEnabled
	return &this
}

// GetName returns the Name field value
func (o *CreateAdvertiserRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateAdvertiserRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateAdvertiserRequest) SetName(v string) {
	o.Name = v
}

// GetAccountStatus returns the AccountStatus field value
func (o *CreateAdvertiserRequest) GetAccountStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountStatus
}

// GetAccountStatusOk returns a tuple with the AccountStatus field value
// and a boolean to check if the value has been set.
func (o *CreateAdvertiserRequest) GetAccountStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountStatus, true
}

// SetAccountStatus sets field value
func (o *CreateAdvertiserRequest) SetAccountStatus(v string) {
	o.AccountStatus = v
}

// GetNetworkEmployeeId returns the NetworkEmployeeId field value
func (o *CreateAdvertiserRequest) GetNetworkEmployeeId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NetworkEmployeeId
}

// GetNetworkEmployeeIdOk returns a tuple with the NetworkEmployeeId field value
// and a boolean to check if the value has been set.
func (o *CreateAdvertiserRequest) GetNetworkEmployeeIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetworkEmployeeId, true
}

// SetNetworkEmployeeId sets field value
func (o *CreateAdvertiserRequest) SetNetworkEmployeeId(v int32) {
	o.NetworkEmployeeId = v
}

// GetInternalNotes returns the InternalNotes field value if set, zero value otherwise.
func (o *CreateAdvertiserRequest) GetInternalNotes() string {
	if o == nil || IsNil(o.InternalNotes) {
		var ret string
		return ret
	}
	return *o.InternalNotes
}

// GetInternalNotesOk returns a tuple with the InternalNotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAdvertiserRequest) GetInternalNotesOk() (*string, bool) {
	if o == nil || IsNil(o.InternalNotes) {
		return nil, false
	}
	return o.InternalNotes, true
}

// HasInternalNotes returns a boolean if a field has been set.
func (o *CreateAdvertiserRequest) HasInternalNotes() bool {
	if o != nil && !IsNil(o.InternalNotes) {
		return true
	}

	return false
}

// SetInternalNotes gets a reference to the given string and assigns it to the InternalNotes field.
func (o *CreateAdvertiserRequest) SetInternalNotes(v string) {
	o.InternalNotes = &v
}

// GetAddressId returns the AddressId field value if set, zero value otherwise.
func (o *CreateAdvertiserRequest) GetAddressId() int32 {
	if o == nil || IsNil(o.AddressId) {
		var ret int32
		return ret
	}
	return *o.AddressId
}

// GetAddressIdOk returns a tuple with the AddressId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAdvertiserRequest) GetAddressIdOk() (*int32, bool) {
	if o == nil || IsNil(o.AddressId) {
		return nil, false
	}
	return o.AddressId, true
}

// HasAddressId returns a boolean if a field has been set.
func (o *CreateAdvertiserRequest) HasAddressId() bool {
	if o != nil && !IsNil(o.AddressId) {
		return true
	}

	return false
}

// SetAddressId gets a reference to the given int32 and assigns it to the AddressId field.
func (o *CreateAdvertiserRequest) SetAddressId(v int32) {
	o.AddressId = &v
}

// GetIsContactAddressEnabled returns the IsContactAddressEnabled field value if set, zero value otherwise.
func (o *CreateAdvertiserRequest) GetIsContactAddressEnabled() bool {
	if o == nil || IsNil(o.IsContactAddressEnabled) {
		var ret bool
		return ret
	}
	return *o.IsContactAddressEnabled
}

// GetIsContactAddressEnabledOk returns a tuple with the IsContactAddressEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAdvertiserRequest) GetIsContactAddressEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsContactAddressEnabled) {
		return nil, false
	}
	return o.IsContactAddressEnabled, true
}

// HasIsContactAddressEnabled returns a boolean if a field has been set.
func (o *CreateAdvertiserRequest) HasIsContactAddressEnabled() bool {
	if o != nil && !IsNil(o.IsContactAddressEnabled) {
		return true
	}

	return false
}

// SetIsContactAddressEnabled gets a reference to the given bool and assigns it to the IsContactAddressEnabled field.
func (o *CreateAdvertiserRequest) SetIsContactAddressEnabled(v bool) {
	o.IsContactAddressEnabled = &v
}

// GetSalesManagerId returns the SalesManagerId field value if set, zero value otherwise.
func (o *CreateAdvertiserRequest) GetSalesManagerId() int32 {
	if o == nil || IsNil(o.SalesManagerId) {
		var ret int32
		return ret
	}
	return *o.SalesManagerId
}

// GetSalesManagerIdOk returns a tuple with the SalesManagerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAdvertiserRequest) GetSalesManagerIdOk() (*int32, bool) {
	if o == nil || IsNil(o.SalesManagerId) {
		return nil, false
	}
	return o.SalesManagerId, true
}

// HasSalesManagerId returns a boolean if a field has been set.
func (o *CreateAdvertiserRequest) HasSalesManagerId() bool {
	if o != nil && !IsNil(o.SalesManagerId) {
		return true
	}

	return false
}

// SetSalesManagerId gets a reference to the given int32 and assigns it to the SalesManagerId field.
func (o *CreateAdvertiserRequest) SetSalesManagerId(v int32) {
	o.SalesManagerId = &v
}

// GetDefaultCurrencyId returns the DefaultCurrencyId field value
func (o *CreateAdvertiserRequest) GetDefaultCurrencyId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DefaultCurrencyId
}

// GetDefaultCurrencyIdOk returns a tuple with the DefaultCurrencyId field value
// and a boolean to check if the value has been set.
func (o *CreateAdvertiserRequest) GetDefaultCurrencyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefaultCurrencyId, true
}

// SetDefaultCurrencyId sets field value
func (o *CreateAdvertiserRequest) SetDefaultCurrencyId(v string) {
	o.DefaultCurrencyId = v
}

// GetPlatformName returns the PlatformName field value if set, zero value otherwise.
func (o *CreateAdvertiserRequest) GetPlatformName() string {
	if o == nil || IsNil(o.PlatformName) {
		var ret string
		return ret
	}
	return *o.PlatformName
}

// GetPlatformNameOk returns a tuple with the PlatformName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAdvertiserRequest) GetPlatformNameOk() (*string, bool) {
	if o == nil || IsNil(o.PlatformName) {
		return nil, false
	}
	return o.PlatformName, true
}

// HasPlatformName returns a boolean if a field has been set.
func (o *CreateAdvertiserRequest) HasPlatformName() bool {
	if o != nil && !IsNil(o.PlatformName) {
		return true
	}

	return false
}

// SetPlatformName gets a reference to the given string and assigns it to the PlatformName field.
func (o *CreateAdvertiserRequest) SetPlatformName(v string) {
	o.PlatformName = &v
}

// GetPlatformUrl returns the PlatformUrl field value if set, zero value otherwise.
func (o *CreateAdvertiserRequest) GetPlatformUrl() string {
	if o == nil || IsNil(o.PlatformUrl) {
		var ret string
		return ret
	}
	return *o.PlatformUrl
}

// GetPlatformUrlOk returns a tuple with the PlatformUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAdvertiserRequest) GetPlatformUrlOk() (*string, bool) {
	if o == nil || IsNil(o.PlatformUrl) {
		return nil, false
	}
	return o.PlatformUrl, true
}

// HasPlatformUrl returns a boolean if a field has been set.
func (o *CreateAdvertiserRequest) HasPlatformUrl() bool {
	if o != nil && !IsNil(o.PlatformUrl) {
		return true
	}

	return false
}

// SetPlatformUrl gets a reference to the given string and assigns it to the PlatformUrl field.
func (o *CreateAdvertiserRequest) SetPlatformUrl(v string) {
	o.PlatformUrl = &v
}

// GetPlatformUsername returns the PlatformUsername field value if set, zero value otherwise.
func (o *CreateAdvertiserRequest) GetPlatformUsername() string {
	if o == nil || IsNil(o.PlatformUsername) {
		var ret string
		return ret
	}
	return *o.PlatformUsername
}

// GetPlatformUsernameOk returns a tuple with the PlatformUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAdvertiserRequest) GetPlatformUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.PlatformUsername) {
		return nil, false
	}
	return o.PlatformUsername, true
}

// HasPlatformUsername returns a boolean if a field has been set.
func (o *CreateAdvertiserRequest) HasPlatformUsername() bool {
	if o != nil && !IsNil(o.PlatformUsername) {
		return true
	}

	return false
}

// SetPlatformUsername gets a reference to the given string and assigns it to the PlatformUsername field.
func (o *CreateAdvertiserRequest) SetPlatformUsername(v string) {
	o.PlatformUsername = &v
}

// GetReportingTimezoneId returns the ReportingTimezoneId field value
func (o *CreateAdvertiserRequest) GetReportingTimezoneId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ReportingTimezoneId
}

// GetReportingTimezoneIdOk returns a tuple with the ReportingTimezoneId field value
// and a boolean to check if the value has been set.
func (o *CreateAdvertiserRequest) GetReportingTimezoneIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReportingTimezoneId, true
}

// SetReportingTimezoneId sets field value
func (o *CreateAdvertiserRequest) SetReportingTimezoneId(v int32) {
	o.ReportingTimezoneId = v
}

// GetAttributionMethod returns the AttributionMethod field value
func (o *CreateAdvertiserRequest) GetAttributionMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AttributionMethod
}

// GetAttributionMethodOk returns a tuple with the AttributionMethod field value
// and a boolean to check if the value has been set.
func (o *CreateAdvertiserRequest) GetAttributionMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttributionMethod, true
}

// SetAttributionMethod sets field value
func (o *CreateAdvertiserRequest) SetAttributionMethod(v string) {
	o.AttributionMethod = v
}

// GetEmailAttributionMethod returns the EmailAttributionMethod field value
func (o *CreateAdvertiserRequest) GetEmailAttributionMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EmailAttributionMethod
}

// GetEmailAttributionMethodOk returns a tuple with the EmailAttributionMethod field value
// and a boolean to check if the value has been set.
func (o *CreateAdvertiserRequest) GetEmailAttributionMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EmailAttributionMethod, true
}

// SetEmailAttributionMethod sets field value
func (o *CreateAdvertiserRequest) SetEmailAttributionMethod(v string) {
	o.EmailAttributionMethod = v
}

// GetAttributionPriority returns the AttributionPriority field value
func (o *CreateAdvertiserRequest) GetAttributionPriority() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AttributionPriority
}

// GetAttributionPriorityOk returns a tuple with the AttributionPriority field value
// and a boolean to check if the value has been set.
func (o *CreateAdvertiserRequest) GetAttributionPriorityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AttributionPriority, true
}

// SetAttributionPriority sets field value
func (o *CreateAdvertiserRequest) SetAttributionPriority(v string) {
	o.AttributionPriority = v
}

// GetAccountingContactEmail returns the AccountingContactEmail field value if set, zero value otherwise.
func (o *CreateAdvertiserRequest) GetAccountingContactEmail() string {
	if o == nil || IsNil(o.AccountingContactEmail) {
		var ret string
		return ret
	}
	return *o.AccountingContactEmail
}

// GetAccountingContactEmailOk returns a tuple with the AccountingContactEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAdvertiserRequest) GetAccountingContactEmailOk() (*string, bool) {
	if o == nil || IsNil(o.AccountingContactEmail) {
		return nil, false
	}
	return o.AccountingContactEmail, true
}

// HasAccountingContactEmail returns a boolean if a field has been set.
func (o *CreateAdvertiserRequest) HasAccountingContactEmail() bool {
	if o != nil && !IsNil(o.AccountingContactEmail) {
		return true
	}

	return false
}

// SetAccountingContactEmail gets a reference to the given string and assigns it to the AccountingContactEmail field.
func (o *CreateAdvertiserRequest) SetAccountingContactEmail(v string) {
	o.AccountingContactEmail = &v
}

// GetVerificationToken returns the VerificationToken field value if set, zero value otherwise.
func (o *CreateAdvertiserRequest) GetVerificationToken() string {
	if o == nil || IsNil(o.VerificationToken) {
		var ret string
		return ret
	}
	return *o.VerificationToken
}

// GetVerificationTokenOk returns a tuple with the VerificationToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAdvertiserRequest) GetVerificationTokenOk() (*string, bool) {
	if o == nil || IsNil(o.VerificationToken) {
		return nil, false
	}
	return o.VerificationToken, true
}

// HasVerificationToken returns a boolean if a field has been set.
func (o *CreateAdvertiserRequest) HasVerificationToken() bool {
	if o != nil && !IsNil(o.VerificationToken) {
		return true
	}

	return false
}

// SetVerificationToken gets a reference to the given string and assigns it to the VerificationToken field.
func (o *CreateAdvertiserRequest) SetVerificationToken(v string) {
	o.VerificationToken = &v
}

// GetOfferIdMacro returns the OfferIdMacro field value if set, zero value otherwise.
func (o *CreateAdvertiserRequest) GetOfferIdMacro() string {
	if o == nil || IsNil(o.OfferIdMacro) {
		var ret string
		return ret
	}
	return *o.OfferIdMacro
}

// GetOfferIdMacroOk returns a tuple with the OfferIdMacro field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAdvertiserRequest) GetOfferIdMacroOk() (*string, bool) {
	if o == nil || IsNil(o.OfferIdMacro) {
		return nil, false
	}
	return o.OfferIdMacro, true
}

// HasOfferIdMacro returns a boolean if a field has been set.
func (o *CreateAdvertiserRequest) HasOfferIdMacro() bool {
	if o != nil && !IsNil(o.OfferIdMacro) {
		return true
	}

	return false
}

// SetOfferIdMacro gets a reference to the given string and assigns it to the OfferIdMacro field.
func (o *CreateAdvertiserRequest) SetOfferIdMacro(v string) {
	o.OfferIdMacro = &v
}

// GetAffiliateIdMacro returns the AffiliateIdMacro field value if set, zero value otherwise.
func (o *CreateAdvertiserRequest) GetAffiliateIdMacro() string {
	if o == nil || IsNil(o.AffiliateIdMacro) {
		var ret string
		return ret
	}
	return *o.AffiliateIdMacro
}

// GetAffiliateIdMacroOk returns a tuple with the AffiliateIdMacro field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAdvertiserRequest) GetAffiliateIdMacroOk() (*string, bool) {
	if o == nil || IsNil(o.AffiliateIdMacro) {
		return nil, false
	}
	return o.AffiliateIdMacro, true
}

// HasAffiliateIdMacro returns a boolean if a field has been set.
func (o *CreateAdvertiserRequest) HasAffiliateIdMacro() bool {
	if o != nil && !IsNil(o.AffiliateIdMacro) {
		return true
	}

	return false
}

// SetAffiliateIdMacro gets a reference to the given string and assigns it to the AffiliateIdMacro field.
func (o *CreateAdvertiserRequest) SetAffiliateIdMacro(v string) {
	o.AffiliateIdMacro = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *CreateAdvertiserRequest) GetLabels() []string {
	if o == nil || IsNil(o.Labels) {
		var ret []string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAdvertiserRequest) GetLabelsOk() ([]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *CreateAdvertiserRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given []string and assigns it to the Labels field.
func (o *CreateAdvertiserRequest) SetLabels(v []string) {
	o.Labels = v
}

// GetUsers returns the Users field value if set, zero value otherwise.
func (o *CreateAdvertiserRequest) GetUsers() []AdvertiserUser {
	if o == nil || IsNil(o.Users) {
		var ret []AdvertiserUser
		return ret
	}
	return o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAdvertiserRequest) GetUsersOk() ([]AdvertiserUser, bool) {
	if o == nil || IsNil(o.Users) {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *CreateAdvertiserRequest) HasUsers() bool {
	if o != nil && !IsNil(o.Users) {
		return true
	}

	return false
}

// SetUsers gets a reference to the given []AdvertiserUser and assigns it to the Users field.
func (o *CreateAdvertiserRequest) SetUsers(v []AdvertiserUser) {
	o.Users = v
}

// GetContactAddress returns the ContactAddress field value if set, zero value otherwise.
func (o *CreateAdvertiserRequest) GetContactAddress() ContactAddress {
	if o == nil || IsNil(o.ContactAddress) {
		var ret ContactAddress
		return ret
	}
	return *o.ContactAddress
}

// GetContactAddressOk returns a tuple with the ContactAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAdvertiserRequest) GetContactAddressOk() (*ContactAddress, bool) {
	if o == nil || IsNil(o.ContactAddress) {
		return nil, false
	}
	return o.ContactAddress, true
}

// HasContactAddress returns a boolean if a field has been set.
func (o *CreateAdvertiserRequest) HasContactAddress() bool {
	if o != nil && !IsNil(o.ContactAddress) {
		return true
	}

	return false
}

// SetContactAddress gets a reference to the given ContactAddress and assigns it to the ContactAddress field.
func (o *CreateAdvertiserRequest) SetContactAddress(v ContactAddress) {
	o.ContactAddress = &v
}

// GetBilling returns the Billing field value if set, zero value otherwise.
func (o *CreateAdvertiserRequest) GetBilling() Billing {
	if o == nil || IsNil(o.Billing) {
		var ret Billing
		return ret
	}
	return *o.Billing
}

// GetBillingOk returns a tuple with the Billing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAdvertiserRequest) GetBillingOk() (*Billing, bool) {
	if o == nil || IsNil(o.Billing) {
		return nil, false
	}
	return o.Billing, true
}

// HasBilling returns a boolean if a field has been set.
func (o *CreateAdvertiserRequest) HasBilling() bool {
	if o != nil && !IsNil(o.Billing) {
		return true
	}

	return false
}

// SetBilling gets a reference to the given Billing and assigns it to the Billing field.
func (o *CreateAdvertiserRequest) SetBilling(v Billing) {
	o.Billing = &v
}

// GetSettings returns the Settings field value if set, zero value otherwise.
func (o *CreateAdvertiserRequest) GetSettings() Settings {
	if o == nil || IsNil(o.Settings) {
		var ret Settings
		return ret
	}
	return *o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAdvertiserRequest) GetSettingsOk() (*Settings, bool) {
	if o == nil || IsNil(o.Settings) {
		return nil, false
	}
	return o.Settings, true
}

// HasSettings returns a boolean if a field has been set.
func (o *CreateAdvertiserRequest) HasSettings() bool {
	if o != nil && !IsNil(o.Settings) {
		return true
	}

	return false
}

// SetSettings gets a reference to the given Settings and assigns it to the Settings field.
func (o *CreateAdvertiserRequest) SetSettings(v Settings) {
	o.Settings = &v
}

func (o CreateAdvertiserRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAdvertiserRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["account_status"] = o.AccountStatus
	toSerialize["network_employee_id"] = o.NetworkEmployeeId
	if !IsNil(o.InternalNotes) {
		toSerialize["internal_notes"] = o.InternalNotes
	}
	if !IsNil(o.AddressId) {
		toSerialize["address_id"] = o.AddressId
	}
	if !IsNil(o.IsContactAddressEnabled) {
		toSerialize["is_contact_address_enabled"] = o.IsContactAddressEnabled
	}
	if !IsNil(o.SalesManagerId) {
		toSerialize["sales_manager_id"] = o.SalesManagerId
	}
	toSerialize["default_currency_id"] = o.DefaultCurrencyId
	if !IsNil(o.PlatformName) {
		toSerialize["platform_name"] = o.PlatformName
	}
	if !IsNil(o.PlatformUrl) {
		toSerialize["platform_url"] = o.PlatformUrl
	}
	if !IsNil(o.PlatformUsername) {
		toSerialize["platform_username"] = o.PlatformUsername
	}
	toSerialize["reporting_timezone_id"] = o.ReportingTimezoneId
	toSerialize["attribution_method"] = o.AttributionMethod
	toSerialize["email_attribution_method"] = o.EmailAttributionMethod
	toSerialize["attribution_priority"] = o.AttributionPriority
	if !IsNil(o.AccountingContactEmail) {
		toSerialize["accounting_contact_email"] = o.AccountingContactEmail
	}
	if !IsNil(o.VerificationToken) {
		toSerialize["verification_token"] = o.VerificationToken
	}
	if !IsNil(o.OfferIdMacro) {
		toSerialize["offer_id_macro"] = o.OfferIdMacro
	}
	if !IsNil(o.AffiliateIdMacro) {
		toSerialize["affiliate_id_macro"] = o.AffiliateIdMacro
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Users) {
		toSerialize["users"] = o.Users
	}
	if !IsNil(o.ContactAddress) {
		toSerialize["contact_address"] = o.ContactAddress
	}
	if !IsNil(o.Billing) {
		toSerialize["billing"] = o.Billing
	}
	if !IsNil(o.Settings) {
		toSerialize["settings"] = o.Settings
	}
	return toSerialize, nil
}

func (o *CreateAdvertiserRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"account_status",
		"network_employee_id",
		"default_currency_id",
		"reporting_timezone_id",
		"attribution_method",
		"email_attribution_method",
		"attribution_priority",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAdvertiserRequest := _CreateAdvertiserRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateAdvertiserRequest)

	if err != nil {
		return err
	}

	*o = CreateAdvertiserRequest(varCreateAdvertiserRequest)

	return err
}

type NullableCreateAdvertiserRequest struct {
	value *CreateAdvertiserRequest
	isSet bool
}

func (v NullableCreateAdvertiserRequest) Get() *CreateAdvertiserRequest {
	return v.value
}

func (v *NullableCreateAdvertiserRequest) Set(val *CreateAdvertiserRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAdvertiserRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAdvertiserRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAdvertiserRequest(val *CreateAdvertiserRequest) *NullableCreateAdvertiserRequest {
	return &NullableCreateAdvertiserRequest{value: val, isSet: true}
}

func (v NullableCreateAdvertiserRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAdvertiserRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


