/*
Everflow Affiliates API

Testing AffiliatesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package affiliate

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_affiliate_AffiliatesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AffiliatesAPIService CreateAffiliate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.AffiliatesAPI.CreateAffiliate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AffiliatesAPIService GetAffiliateById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var affiliateId int32

		resp, httpRes, err := apiClient.AffiliatesAPI.GetAffiliateById(context.Background(), affiliateId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test AffiliatesAPIService UpdateAffiliate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var affiliateId int32

		resp, httpRes, err := apiClient.AffiliatesAPI.UpdateAffiliate(context.Background(), affiliateId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
