apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-

resources:
- ../../base
- migration-job.yaml
- cluster-issuer.yaml
- backend-config.yaml
- managed-certificate.yaml

patches:
- path: patches/deployment-patch.yaml
- path: patches/ingress-patch.yaml

images:
- name: europe-west1-docker.pkg.dev/jinko-test/jinko-test-docker-repo/saas-app
  newTag: 0.0.4