apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/cert-manager/cert-manager/releases/download/v1.13.2/cert-manager.yaml
- leader-election-rbac.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: cert-manager
    namespace: cert-manager
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --leader-election-namespace=cert-manager
- target:
    group: apps
    version: v1
    kind: Deployment
    name: cert-manager-cainjector
    namespace: cert-manager
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/args/-
      value: --leader-election-namespace=cert-manager
- target:
    group: admissionregistration.k8s.io
    version: v1
    kind: ValidatingWebhookConfiguration
    name: cert-manager-webhook
  patch: |-
    - op: replace
      path: /webhooks/0/failurePolicy
      value: Ignore
- target:
    group: admissionregistration.k8s.io
    version: v1
    kind: MutatingWebhookConfiguration
    name: cert-manager-webhook
  patch: |-
    - op: replace
      path: /webhooks/0/failurePolicy
      value: Ignore