/*
Everflow Affiliates API

API for managing affiliates in the Everflow platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate

import (
	"encoding/json"
)

// checks if the AffiliateWithRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AffiliateWithRelationships{}

// AffiliateWithRelationships struct for AffiliateWithRelationships
type AffiliateWithRelationships struct {
	// The unique ID of the affiliate
	NetworkAffiliateId *int32 `json:"network_affiliate_id,omitempty"`
	// The network ID
	NetworkId *int32 `json:"network_id,omitempty"`
	// The name of the affiliate
	Name *string `json:"name,omitempty"`
	// The affiliate's account status
	AccountStatus *string `json:"account_status,omitempty"`
	// The employee id of the account manager
	NetworkEmployeeId *int32 `json:"network_employee_id,omitempty"`
	// The account manager ID
	AccountManagerId *int32 `json:"account_manager_id,omitempty"`
	// The account manager's name
	AccountManagerName *string `json:"account_manager_name,omitempty"`
	// Account executive ID
	AccountExecutiveId *int32 `json:"account_executive_id,omitempty"`
	// The account executive's name
	AccountExecutiveName *string `json:"account_executive_name,omitempty"`
	// Internal notes
	InternalNotes *string `json:"internal_notes,omitempty"`
	// Whether the affiliate has notifications enabled
	HasNotifications *bool `json:"has_notifications,omitempty"`
	// Traffic source ID
	NetworkTrafficSourceId *int32 `json:"network_traffic_source_id,omitempty"`
	// Address ID (note the typo in the field name)
	AdressId *int32 `json:"adress_id,omitempty"`
	// Default currency code
	DefaultCurrencyId *string `json:"default_currency_id,omitempty"`
	// Whether contact address is enabled
	IsContactAddressEnabled *bool `json:"is_contact_address_enabled,omitempty"`
	// Whether media cost tracking links are enabled
	EnableMediaCostTrackingLinks *bool `json:"enable_media_cost_tracking_links,omitempty"`
	// Today's revenue (formatted as currency string)
	TodayRevenue *string `json:"today_revenue,omitempty"`
	// Unix timestamp of creation
	TimeCreated *int64 `json:"time_created,omitempty"`
	// Unix timestamp of last save
	TimeSaved *int64 `json:"time_saved,omitempty"`
	// Array of labels associated with the affiliate
	Labels []string `json:"labels,omitempty"`
	// The affiliate's balance
	Balance *float32 `json:"balance,omitempty"`
	// Unix timestamp of last login
	LastLogin *int64 `json:"last_login,omitempty"`
	// Global tracking domain URL
	GlobalTrackingDomainUrl *string `json:"global_tracking_domain_url,omitempty"`
	// Network country code
	NetworkCountryCode *string `json:"network_country_code,omitempty"`
	// Whether the affiliate is payable
	IsPayable *bool `json:"is_payable,omitempty"`
	// The payment type
	PaymentType *string `json:"payment_type,omitempty"`
	// ID of referring affiliate
	ReferrerId   *int32                                       `json:"referrer_id,omitempty"`
	Relationship *AffiliateWithRelationshipsAllOfRelationship `json:"relationship,omitempty"`
}

// NewAffiliateWithRelationships instantiates a new AffiliateWithRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAffiliateWithRelationships() *AffiliateWithRelationships {
	this := AffiliateWithRelationships{}
	return &this
}

// NewAffiliateWithRelationshipsWithDefaults instantiates a new AffiliateWithRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAffiliateWithRelationshipsWithDefaults() *AffiliateWithRelationships {
	this := AffiliateWithRelationships{}
	return &this
}

// GetNetworkAffiliateId returns the NetworkAffiliateId field value if set, zero value otherwise.
func (o *AffiliateWithRelationships) GetNetworkAffiliateId() int32 {
	if o == nil || IsNil(o.NetworkAffiliateId) {
		var ret int32
		return ret
	}
	return *o.NetworkAffiliateId
}

// GetNetworkAffiliateIdOk returns a tuple with the NetworkAffiliateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateWithRelationships) GetNetworkAffiliateIdOk() (*int32, bool) {
	if o == nil || IsNil(o.NetworkAffiliateId) {
		return nil, false
	}
	return o.NetworkAffiliateId, true
}

// HasNetworkAffiliateId returns a boolean if a field has been set.
func (o *AffiliateWithRelationships) HasNetworkAffiliateId() bool {
	if o != nil && !IsNil(o.NetworkAffiliateId) {
		return true
	}

	return false
}

// SetNetworkAffiliateId gets a reference to the given int32 and assigns it to the NetworkAffiliateId field.
func (o *AffiliateWithRelationships) SetNetworkAffiliateId(v int32) {
	o.NetworkAffiliateId = &v
}

// GetNetworkId returns the NetworkId field value if set, zero value otherwise.
func (o *AffiliateWithRelationships) GetNetworkId() int32 {
	if o == nil || IsNil(o.NetworkId) {
		var ret int32
		return ret
	}
	return *o.NetworkId
}

// GetNetworkIdOk returns a tuple with the NetworkId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateWithRelationships) GetNetworkIdOk() (*int32, bool) {
	if o == nil || IsNil(o.NetworkId) {
		return nil, false
	}
	return o.NetworkId, true
}

// HasNetworkId returns a boolean if a field has been set.
func (o *AffiliateWithRelationships) HasNetworkId() bool {
	if o != nil && !IsNil(o.NetworkId) {
		return true
	}

	return false
}

// SetNetworkId gets a reference to the given int32 and assigns it to the NetworkId field.
func (o *AffiliateWithRelationships) SetNetworkId(v int32) {
	o.NetworkId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AffiliateWithRelationships) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateWithRelationships) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AffiliateWithRelationships) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AffiliateWithRelationships) SetName(v string) {
	o.Name = &v
}

// GetAccountStatus returns the AccountStatus field value if set, zero value otherwise.
func (o *AffiliateWithRelationships) GetAccountStatus() string {
	if o == nil || IsNil(o.AccountStatus) {
		var ret string
		return ret
	}
	return *o.AccountStatus
}

// GetAccountStatusOk returns a tuple with the AccountStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateWithRelationships) GetAccountStatusOk() (*string, bool) {
	if o == nil || IsNil(o.AccountStatus) {
		return nil, false
	}
	return o.AccountStatus, true
}

// HasAccountStatus returns a boolean if a field has been set.
func (o *AffiliateWithRelationships) HasAccountStatus() bool {
	if o != nil && !IsNil(o.AccountStatus) {
		return true
	}

	return false
}

// SetAccountStatus gets a reference to the given string and assigns it to the AccountStatus field.
func (o *AffiliateWithRelationships) SetAccountStatus(v string) {
	o.AccountStatus = &v
}

// GetNetworkEmployeeId returns the NetworkEmployeeId field value if set, zero value otherwise.
func (o *AffiliateWithRelationships) GetNetworkEmployeeId() int32 {
	if o == nil || IsNil(o.NetworkEmployeeId) {
		var ret int32
		return ret
	}
	return *o.NetworkEmployeeId
}

// GetNetworkEmployeeIdOk returns a tuple with the NetworkEmployeeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateWithRelationships) GetNetworkEmployeeIdOk() (*int32, bool) {
	if o == nil || IsNil(o.NetworkEmployeeId) {
		return nil, false
	}
	return o.NetworkEmployeeId, true
}

// HasNetworkEmployeeId returns a boolean if a field has been set.
func (o *AffiliateWithRelationships) HasNetworkEmployeeId() bool {
	if o != nil && !IsNil(o.NetworkEmployeeId) {
		return true
	}

	return false
}

// SetNetworkEmployeeId gets a reference to the given int32 and assigns it to the NetworkEmployeeId field.
func (o *AffiliateWithRelationships) SetNetworkEmployeeId(v int32) {
	o.NetworkEmployeeId = &v
}

// GetAccountManagerId returns the AccountManagerId field value if set, zero value otherwise.
func (o *AffiliateWithRelationships) GetAccountManagerId() int32 {
	if o == nil || IsNil(o.AccountManagerId) {
		var ret int32
		return ret
	}
	return *o.AccountManagerId
}

// GetAccountManagerIdOk returns a tuple with the AccountManagerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateWithRelationships) GetAccountManagerIdOk() (*int32, bool) {
	if o == nil || IsNil(o.AccountManagerId) {
		return nil, false
	}
	return o.AccountManagerId, true
}

// HasAccountManagerId returns a boolean if a field has been set.
func (o *AffiliateWithRelationships) HasAccountManagerId() bool {
	if o != nil && !IsNil(o.AccountManagerId) {
		return true
	}

	return false
}

// SetAccountManagerId gets a reference to the given int32 and assigns it to the AccountManagerId field.
func (o *AffiliateWithRelationships) SetAccountManagerId(v int32) {
	o.AccountManagerId = &v
}

// GetAccountManagerName returns the AccountManagerName field value if set, zero value otherwise.
func (o *AffiliateWithRelationships) GetAccountManagerName() string {
	if o == nil || IsNil(o.AccountManagerName) {
		var ret string
		return ret
	}
	return *o.AccountManagerName
}

// GetAccountManagerNameOk returns a tuple with the AccountManagerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateWithRelationships) GetAccountManagerNameOk() (*string, bool) {
	if o == nil || IsNil(o.AccountManagerName) {
		return nil, false
	}
	return o.AccountManagerName, true
}

// HasAccountManagerName returns a boolean if a field has been set.
func (o *AffiliateWithRelationships) HasAccountManagerName() bool {
	if o != nil && !IsNil(o.AccountManagerName) {
		return true
	}

	return false
}

// SetAccountManagerName gets a reference to the given string and assigns it to the AccountManagerName field.
func (o *AffiliateWithRelationships) SetAccountManagerName(v string) {
	o.AccountManagerName = &v
}

// GetAccountExecutiveId returns the AccountExecutiveId field value if set, zero value otherwise.
func (o *AffiliateWithRelationships) GetAccountExecutiveId() int32 {
	if o == nil || IsNil(o.AccountExecutiveId) {
		var ret int32
		return ret
	}
	return *o.AccountExecutiveId
}

// GetAccountExecutiveIdOk returns a tuple with the AccountExecutiveId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateWithRelationships) GetAccountExecutiveIdOk() (*int32, bool) {
	if o == nil || IsNil(o.AccountExecutiveId) {
		return nil, false
	}
	return o.AccountExecutiveId, true
}

// HasAccountExecutiveId returns a boolean if a field has been set.
func (o *AffiliateWithRelationships) HasAccountExecutiveId() bool {
	if o != nil && !IsNil(o.AccountExecutiveId) {
		return true
	}

	return false
}

// SetAccountExecutiveId gets a reference to the given int32 and assigns it to the AccountExecutiveId field.
func (o *AffiliateWithRelationships) SetAccountExecutiveId(v int32) {
	o.AccountExecutiveId = &v
}

// GetAccountExecutiveName returns the AccountExecutiveName field value if set, zero value otherwise.
func (o *AffiliateWithRelationships) GetAccountExecutiveName() string {
	if o == nil || IsNil(o.AccountExecutiveName) {
		var ret string
		return ret
	}
	return *o.AccountExecutiveName
}

// GetAccountExecutiveNameOk returns a tuple with the AccountExecutiveName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateWithRelationships) GetAccountExecutiveNameOk() (*string, bool) {
	if o == nil || IsNil(o.AccountExecutiveName) {
		return nil, false
	}
	return o.AccountExecutiveName, true
}

// HasAccountExecutiveName returns a boolean if a field has been set.
func (o *AffiliateWithRelationships) HasAccountExecutiveName() bool {
	if o != nil && !IsNil(o.AccountExecutiveName) {
		return true
	}

	return false
}

// SetAccountExecutiveName gets a reference to the given string and assigns it to the AccountExecutiveName field.
func (o *AffiliateWithRelationships) SetAccountExecutiveName(v string) {
	o.AccountExecutiveName = &v
}

// GetInternalNotes returns the InternalNotes field value if set, zero value otherwise.
func (o *AffiliateWithRelationships) GetInternalNotes() string {
	if o == nil || IsNil(o.InternalNotes) {
		var ret string
		return ret
	}
	return *o.InternalNotes
}

// GetInternalNotesOk returns a tuple with the InternalNotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateWithRelationships) GetInternalNotesOk() (*string, bool) {
	if o == nil || IsNil(o.InternalNotes) {
		return nil, false
	}
	return o.InternalNotes, true
}

// HasInternalNotes returns a boolean if a field has been set.
func (o *AffiliateWithRelationships) HasInternalNotes() bool {
	if o != nil && !IsNil(o.InternalNotes) {
		return true
	}

	return false
}

// SetInternalNotes gets a reference to the given string and assigns it to the InternalNotes field.
func (o *AffiliateWithRelationships) SetInternalNotes(v string) {
	o.InternalNotes = &v
}

// GetHasNotifications returns the HasNotifications field value if set, zero value otherwise.
func (o *AffiliateWithRelationships) GetHasNotifications() bool {
	if o == nil || IsNil(o.HasNotifications) {
		var ret bool
		return ret
	}
	return *o.HasNotifications
}

// GetHasNotificationsOk returns a tuple with the HasNotifications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateWithRelationships) GetHasNotificationsOk() (*bool, bool) {
	if o == nil || IsNil(o.HasNotifications) {
		return nil, false
	}
	return o.HasNotifications, true
}

// HasHasNotifications returns a boolean if a field has been set.
func (o *AffiliateWithRelationships) HasHasNotifications() bool {
	if o != nil && !IsNil(o.HasNotifications) {
		return true
	}

	return false
}

// SetHasNotifications gets a reference to the given bool and assigns it to the HasNotifications field.
func (o *AffiliateWithRelationships) SetHasNotifications(v bool) {
	o.HasNotifications = &v
}

// GetNetworkTrafficSourceId returns the NetworkTrafficSourceId field value if set, zero value otherwise.
func (o *AffiliateWithRelationships) GetNetworkTrafficSourceId() int32 {
	if o == nil || IsNil(o.NetworkTrafficSourceId) {
		var ret int32
		return ret
	}
	return *o.NetworkTrafficSourceId
}

// GetNetworkTrafficSourceIdOk returns a tuple with the NetworkTrafficSourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateWithRelationships) GetNetworkTrafficSourceIdOk() (*int32, bool) {
	if o == nil || IsNil(o.NetworkTrafficSourceId) {
		return nil, false
	}
	return o.NetworkTrafficSourceId, true
}

// HasNetworkTrafficSourceId returns a boolean if a field has been set.
func (o *AffiliateWithRelationships) HasNetworkTrafficSourceId() bool {
	if o != nil && !IsNil(o.NetworkTrafficSourceId) {
		return true
	}

	return false
}

// SetNetworkTrafficSourceId gets a reference to the given int32 and assigns it to the NetworkTrafficSourceId field.
func (o *AffiliateWithRelationships) SetNetworkTrafficSourceId(v int32) {
	o.NetworkTrafficSourceId = &v
}

// GetAdressId returns the AdressId field value if set, zero value otherwise.
func (o *AffiliateWithRelationships) GetAdressId() int32 {
	if o == nil || IsNil(o.AdressId) {
		var ret int32
		return ret
	}
	return *o.AdressId
}

// GetAdressIdOk returns a tuple with the AdressId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateWithRelationships) GetAdressIdOk() (*int32, bool) {
	if o == nil || IsNil(o.AdressId) {
		return nil, false
	}
	return o.AdressId, true
}

// HasAdressId returns a boolean if a field has been set.
func (o *AffiliateWithRelationships) HasAdressId() bool {
	if o != nil && !IsNil(o.AdressId) {
		return true
	}

	return false
}

// SetAdressId gets a reference to the given int32 and assigns it to the AdressId field.
func (o *AffiliateWithRelationships) SetAdressId(v int32) {
	o.AdressId = &v
}

// GetDefaultCurrencyId returns the DefaultCurrencyId field value if set, zero value otherwise.
func (o *AffiliateWithRelationships) GetDefaultCurrencyId() string {
	if o == nil || IsNil(o.DefaultCurrencyId) {
		var ret string
		return ret
	}
	return *o.DefaultCurrencyId
}

// GetDefaultCurrencyIdOk returns a tuple with the DefaultCurrencyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateWithRelationships) GetDefaultCurrencyIdOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultCurrencyId) {
		return nil, false
	}
	return o.DefaultCurrencyId, true
}

// HasDefaultCurrencyId returns a boolean if a field has been set.
func (o *AffiliateWithRelationships) HasDefaultCurrencyId() bool {
	if o != nil && !IsNil(o.DefaultCurrencyId) {
		return true
	}

	return false
}

// SetDefaultCurrencyId gets a reference to the given string and assigns it to the DefaultCurrencyId field.
func (o *AffiliateWithRelationships) SetDefaultCurrencyId(v string) {
	o.DefaultCurrencyId = &v
}

// GetIsContactAddressEnabled returns the IsContactAddressEnabled field value if set, zero value otherwise.
func (o *AffiliateWithRelationships) GetIsContactAddressEnabled() bool {
	if o == nil || IsNil(o.IsContactAddressEnabled) {
		var ret bool
		return ret
	}
	return *o.IsContactAddressEnabled
}

// GetIsContactAddressEnabledOk returns a tuple with the IsContactAddressEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateWithRelationships) GetIsContactAddressEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsContactAddressEnabled) {
		return nil, false
	}
	return o.IsContactAddressEnabled, true
}

// HasIsContactAddressEnabled returns a boolean if a field has been set.
func (o *AffiliateWithRelationships) HasIsContactAddressEnabled() bool {
	if o != nil && !IsNil(o.IsContactAddressEnabled) {
		return true
	}

	return false
}

// SetIsContactAddressEnabled gets a reference to the given bool and assigns it to the IsContactAddressEnabled field.
func (o *AffiliateWithRelationships) SetIsContactAddressEnabled(v bool) {
	o.IsContactAddressEnabled = &v
}

// GetEnableMediaCostTrackingLinks returns the EnableMediaCostTrackingLinks field value if set, zero value otherwise.
func (o *AffiliateWithRelationships) GetEnableMediaCostTrackingLinks() bool {
	if o == nil || IsNil(o.EnableMediaCostTrackingLinks) {
		var ret bool
		return ret
	}
	return *o.EnableMediaCostTrackingLinks
}

// GetEnableMediaCostTrackingLinksOk returns a tuple with the EnableMediaCostTrackingLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateWithRelationships) GetEnableMediaCostTrackingLinksOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableMediaCostTrackingLinks) {
		return nil, false
	}
	return o.EnableMediaCostTrackingLinks, true
}

// HasEnableMediaCostTrackingLinks returns a boolean if a field has been set.
func (o *AffiliateWithRelationships) HasEnableMediaCostTrackingLinks() bool {
	if o != nil && !IsNil(o.EnableMediaCostTrackingLinks) {
		return true
	}

	return false
}

// SetEnableMediaCostTrackingLinks gets a reference to the given bool and assigns it to the EnableMediaCostTrackingLinks field.
func (o *AffiliateWithRelationships) SetEnableMediaCostTrackingLinks(v bool) {
	o.EnableMediaCostTrackingLinks = &v
}

// GetTodayRevenue returns the TodayRevenue field value if set, zero value otherwise.
func (o *AffiliateWithRelationships) GetTodayRevenue() string {
	if o == nil || IsNil(o.TodayRevenue) {
		var ret string
		return ret
	}
	return *o.TodayRevenue
}

// GetTodayRevenueOk returns a tuple with the TodayRevenue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateWithRelationships) GetTodayRevenueOk() (*string, bool) {
	if o == nil || IsNil(o.TodayRevenue) {
		return nil, false
	}
	return o.TodayRevenue, true
}

// HasTodayRevenue returns a boolean if a field has been set.
func (o *AffiliateWithRelationships) HasTodayRevenue() bool {
	if o != nil && !IsNil(o.TodayRevenue) {
		return true
	}

	return false
}

// SetTodayRevenue gets a reference to the given string and assigns it to the TodayRevenue field.
func (o *AffiliateWithRelationships) SetTodayRevenue(v string) {
	o.TodayRevenue = &v
}

// GetTimeCreated returns the TimeCreated field value if set, zero value otherwise.
func (o *AffiliateWithRelationships) GetTimeCreated() int64 {
	if o == nil || IsNil(o.TimeCreated) {
		var ret int64
		return ret
	}
	return *o.TimeCreated
}

// GetTimeCreatedOk returns a tuple with the TimeCreated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateWithRelationships) GetTimeCreatedOk() (*int64, bool) {
	if o == nil || IsNil(o.TimeCreated) {
		return nil, false
	}
	return o.TimeCreated, true
}

// HasTimeCreated returns a boolean if a field has been set.
func (o *AffiliateWithRelationships) HasTimeCreated() bool {
	if o != nil && !IsNil(o.TimeCreated) {
		return true
	}

	return false
}

// SetTimeCreated gets a reference to the given int64 and assigns it to the TimeCreated field.
func (o *AffiliateWithRelationships) SetTimeCreated(v int64) {
	o.TimeCreated = &v
}

// GetTimeSaved returns the TimeSaved field value if set, zero value otherwise.
func (o *AffiliateWithRelationships) GetTimeSaved() int64 {
	if o == nil || IsNil(o.TimeSaved) {
		var ret int64
		return ret
	}
	return *o.TimeSaved
}

// GetTimeSavedOk returns a tuple with the TimeSaved field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateWithRelationships) GetTimeSavedOk() (*int64, bool) {
	if o == nil || IsNil(o.TimeSaved) {
		return nil, false
	}
	return o.TimeSaved, true
}

// HasTimeSaved returns a boolean if a field has been set.
func (o *AffiliateWithRelationships) HasTimeSaved() bool {
	if o != nil && !IsNil(o.TimeSaved) {
		return true
	}

	return false
}

// SetTimeSaved gets a reference to the given int64 and assigns it to the TimeSaved field.
func (o *AffiliateWithRelationships) SetTimeSaved(v int64) {
	o.TimeSaved = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *AffiliateWithRelationships) GetLabels() []string {
	if o == nil || IsNil(o.Labels) {
		var ret []string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateWithRelationships) GetLabelsOk() ([]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *AffiliateWithRelationships) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given []string and assigns it to the Labels field.
func (o *AffiliateWithRelationships) SetLabels(v []string) {
	o.Labels = v
}

// GetBalance returns the Balance field value if set, zero value otherwise.
func (o *AffiliateWithRelationships) GetBalance() float32 {
	if o == nil || IsNil(o.Balance) {
		var ret float32
		return ret
	}
	return *o.Balance
}

// GetBalanceOk returns a tuple with the Balance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateWithRelationships) GetBalanceOk() (*float32, bool) {
	if o == nil || IsNil(o.Balance) {
		return nil, false
	}
	return o.Balance, true
}

// HasBalance returns a boolean if a field has been set.
func (o *AffiliateWithRelationships) HasBalance() bool {
	if o != nil && !IsNil(o.Balance) {
		return true
	}

	return false
}

// SetBalance gets a reference to the given float32 and assigns it to the Balance field.
func (o *AffiliateWithRelationships) SetBalance(v float32) {
	o.Balance = &v
}

// GetLastLogin returns the LastLogin field value if set, zero value otherwise.
func (o *AffiliateWithRelationships) GetLastLogin() int64 {
	if o == nil || IsNil(o.LastLogin) {
		var ret int64
		return ret
	}
	return *o.LastLogin
}

// GetLastLoginOk returns a tuple with the LastLogin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateWithRelationships) GetLastLoginOk() (*int64, bool) {
	if o == nil || IsNil(o.LastLogin) {
		return nil, false
	}
	return o.LastLogin, true
}

// HasLastLogin returns a boolean if a field has been set.
func (o *AffiliateWithRelationships) HasLastLogin() bool {
	if o != nil && !IsNil(o.LastLogin) {
		return true
	}

	return false
}

// SetLastLogin gets a reference to the given int64 and assigns it to the LastLogin field.
func (o *AffiliateWithRelationships) SetLastLogin(v int64) {
	o.LastLogin = &v
}

// GetGlobalTrackingDomainUrl returns the GlobalTrackingDomainUrl field value if set, zero value otherwise.
func (o *AffiliateWithRelationships) GetGlobalTrackingDomainUrl() string {
	if o == nil || IsNil(o.GlobalTrackingDomainUrl) {
		var ret string
		return ret
	}
	return *o.GlobalTrackingDomainUrl
}

// GetGlobalTrackingDomainUrlOk returns a tuple with the GlobalTrackingDomainUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateWithRelationships) GetGlobalTrackingDomainUrlOk() (*string, bool) {
	if o == nil || IsNil(o.GlobalTrackingDomainUrl) {
		return nil, false
	}
	return o.GlobalTrackingDomainUrl, true
}

// HasGlobalTrackingDomainUrl returns a boolean if a field has been set.
func (o *AffiliateWithRelationships) HasGlobalTrackingDomainUrl() bool {
	if o != nil && !IsNil(o.GlobalTrackingDomainUrl) {
		return true
	}

	return false
}

// SetGlobalTrackingDomainUrl gets a reference to the given string and assigns it to the GlobalTrackingDomainUrl field.
func (o *AffiliateWithRelationships) SetGlobalTrackingDomainUrl(v string) {
	o.GlobalTrackingDomainUrl = &v
}

// GetNetworkCountryCode returns the NetworkCountryCode field value if set, zero value otherwise.
func (o *AffiliateWithRelationships) GetNetworkCountryCode() string {
	if o == nil || IsNil(o.NetworkCountryCode) {
		var ret string
		return ret
	}
	return *o.NetworkCountryCode
}

// GetNetworkCountryCodeOk returns a tuple with the NetworkCountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateWithRelationships) GetNetworkCountryCodeOk() (*string, bool) {
	if o == nil || IsNil(o.NetworkCountryCode) {
		return nil, false
	}
	return o.NetworkCountryCode, true
}

// HasNetworkCountryCode returns a boolean if a field has been set.
func (o *AffiliateWithRelationships) HasNetworkCountryCode() bool {
	if o != nil && !IsNil(o.NetworkCountryCode) {
		return true
	}

	return false
}

// SetNetworkCountryCode gets a reference to the given string and assigns it to the NetworkCountryCode field.
func (o *AffiliateWithRelationships) SetNetworkCountryCode(v string) {
	o.NetworkCountryCode = &v
}

// GetIsPayable returns the IsPayable field value if set, zero value otherwise.
func (o *AffiliateWithRelationships) GetIsPayable() bool {
	if o == nil || IsNil(o.IsPayable) {
		var ret bool
		return ret
	}
	return *o.IsPayable
}

// GetIsPayableOk returns a tuple with the IsPayable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateWithRelationships) GetIsPayableOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPayable) {
		return nil, false
	}
	return o.IsPayable, true
}

// HasIsPayable returns a boolean if a field has been set.
func (o *AffiliateWithRelationships) HasIsPayable() bool {
	if o != nil && !IsNil(o.IsPayable) {
		return true
	}

	return false
}

// SetIsPayable gets a reference to the given bool and assigns it to the IsPayable field.
func (o *AffiliateWithRelationships) SetIsPayable(v bool) {
	o.IsPayable = &v
}

// GetPaymentType returns the PaymentType field value if set, zero value otherwise.
func (o *AffiliateWithRelationships) GetPaymentType() string {
	if o == nil || IsNil(o.PaymentType) {
		var ret string
		return ret
	}
	return *o.PaymentType
}

// GetPaymentTypeOk returns a tuple with the PaymentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateWithRelationships) GetPaymentTypeOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentType) {
		return nil, false
	}
	return o.PaymentType, true
}

// HasPaymentType returns a boolean if a field has been set.
func (o *AffiliateWithRelationships) HasPaymentType() bool {
	if o != nil && !IsNil(o.PaymentType) {
		return true
	}

	return false
}

// SetPaymentType gets a reference to the given string and assigns it to the PaymentType field.
func (o *AffiliateWithRelationships) SetPaymentType(v string) {
	o.PaymentType = &v
}

// GetReferrerId returns the ReferrerId field value if set, zero value otherwise.
func (o *AffiliateWithRelationships) GetReferrerId() int32 {
	if o == nil || IsNil(o.ReferrerId) {
		var ret int32
		return ret
	}
	return *o.ReferrerId
}

// GetReferrerIdOk returns a tuple with the ReferrerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateWithRelationships) GetReferrerIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ReferrerId) {
		return nil, false
	}
	return o.ReferrerId, true
}

// HasReferrerId returns a boolean if a field has been set.
func (o *AffiliateWithRelationships) HasReferrerId() bool {
	if o != nil && !IsNil(o.ReferrerId) {
		return true
	}

	return false
}

// SetReferrerId gets a reference to the given int32 and assigns it to the ReferrerId field.
func (o *AffiliateWithRelationships) SetReferrerId(v int32) {
	o.ReferrerId = &v
}

// GetRelationship returns the Relationship field value if set, zero value otherwise.
func (o *AffiliateWithRelationships) GetRelationship() AffiliateWithRelationshipsAllOfRelationship {
	if o == nil || IsNil(o.Relationship) {
		var ret AffiliateWithRelationshipsAllOfRelationship
		return ret
	}
	return *o.Relationship
}

// GetRelationshipOk returns a tuple with the Relationship field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AffiliateWithRelationships) GetRelationshipOk() (*AffiliateWithRelationshipsAllOfRelationship, bool) {
	if o == nil || IsNil(o.Relationship) {
		return nil, false
	}
	return o.Relationship, true
}

// HasRelationship returns a boolean if a field has been set.
func (o *AffiliateWithRelationships) HasRelationship() bool {
	if o != nil && !IsNil(o.Relationship) {
		return true
	}

	return false
}

// SetRelationship gets a reference to the given AffiliateWithRelationshipsAllOfRelationship and assigns it to the Relationship field.
func (o *AffiliateWithRelationships) SetRelationship(v AffiliateWithRelationshipsAllOfRelationship) {
	o.Relationship = &v
}

func (o AffiliateWithRelationships) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AffiliateWithRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NetworkAffiliateId) {
		toSerialize["network_affiliate_id"] = o.NetworkAffiliateId
	}
	if !IsNil(o.NetworkId) {
		toSerialize["network_id"] = o.NetworkId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.AccountStatus) {
		toSerialize["account_status"] = o.AccountStatus
	}
	if !IsNil(o.NetworkEmployeeId) {
		toSerialize["network_employee_id"] = o.NetworkEmployeeId
	}
	if !IsNil(o.AccountManagerId) {
		toSerialize["account_manager_id"] = o.AccountManagerId
	}
	if !IsNil(o.AccountManagerName) {
		toSerialize["account_manager_name"] = o.AccountManagerName
	}
	if !IsNil(o.AccountExecutiveId) {
		toSerialize["account_executive_id"] = o.AccountExecutiveId
	}
	if !IsNil(o.AccountExecutiveName) {
		toSerialize["account_executive_name"] = o.AccountExecutiveName
	}
	if !IsNil(o.InternalNotes) {
		toSerialize["internal_notes"] = o.InternalNotes
	}
	if !IsNil(o.HasNotifications) {
		toSerialize["has_notifications"] = o.HasNotifications
	}
	if !IsNil(o.NetworkTrafficSourceId) {
		toSerialize["network_traffic_source_id"] = o.NetworkTrafficSourceId
	}
	if !IsNil(o.AdressId) {
		toSerialize["adress_id"] = o.AdressId
	}
	if !IsNil(o.DefaultCurrencyId) {
		toSerialize["default_currency_id"] = o.DefaultCurrencyId
	}
	if !IsNil(o.IsContactAddressEnabled) {
		toSerialize["is_contact_address_enabled"] = o.IsContactAddressEnabled
	}
	if !IsNil(o.EnableMediaCostTrackingLinks) {
		toSerialize["enable_media_cost_tracking_links"] = o.EnableMediaCostTrackingLinks
	}
	if !IsNil(o.TodayRevenue) {
		toSerialize["today_revenue"] = o.TodayRevenue
	}
	if !IsNil(o.TimeCreated) {
		toSerialize["time_created"] = o.TimeCreated
	}
	if !IsNil(o.TimeSaved) {
		toSerialize["time_saved"] = o.TimeSaved
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Balance) {
		toSerialize["balance"] = o.Balance
	}
	if !IsNil(o.LastLogin) {
		toSerialize["last_login"] = o.LastLogin
	}
	if !IsNil(o.GlobalTrackingDomainUrl) {
		toSerialize["global_tracking_domain_url"] = o.GlobalTrackingDomainUrl
	}
	if !IsNil(o.NetworkCountryCode) {
		toSerialize["network_country_code"] = o.NetworkCountryCode
	}
	if !IsNil(o.IsPayable) {
		toSerialize["is_payable"] = o.IsPayable
	}
	if !IsNil(o.PaymentType) {
		toSerialize["payment_type"] = o.PaymentType
	}
	if !IsNil(o.ReferrerId) {
		toSerialize["referrer_id"] = o.ReferrerId
	}
	if !IsNil(o.Relationship) {
		toSerialize["relationship"] = o.Relationship
	}
	return toSerialize, nil
}

type NullableAffiliateWithRelationships struct {
	value *AffiliateWithRelationships
	isSet bool
}

func (v NullableAffiliateWithRelationships) Get() *AffiliateWithRelationships {
	return v.value
}

func (v *NullableAffiliateWithRelationships) Set(val *AffiliateWithRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableAffiliateWithRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableAffiliateWithRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAffiliateWithRelationships(val *AffiliateWithRelationships) *NullableAffiliateWithRelationships {
	return &NullableAffiliateWithRelationships{value: val, isSet: true}
}

func (v NullableAffiliateWithRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAffiliateWithRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
