/*
Everflow Affiliates API

API for managing affiliates in the Everflow platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate

import (
	"encoding/json"
)

// checks if the BillingInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingInfo{}

// BillingInfo struct for BillingInfo
type BillingInfo struct {
	// The affiliate's invoicing frequency
	BillingFrequency *string `json:"billing_frequency,omitempty"`
	// The affiliate's payment type
	PaymentType *string `json:"payment_type,omitempty"`
	// The affiliate's tax id
	TaxId *string `json:"tax_id,omitempty"`
	// Configures automatic invoice creations
	IsInvoiceCreationAuto *bool `json:"is_invoice_creation_auto,omitempty"`
	// Automatic invoice creation start date (YYYY-mm-dd)
	AutoInvoiceStartDate *string `json:"auto_invoice_start_date,omitempty"`
	// Whether invoices are hidden from the affiliate by default
	DefaultInvoiceIsHidden *bool `json:"default_invoice_is_hidden,omitempty"`
	// Days to wait for invoice generation after billing period
	InvoiceGenerationDaysDelay *int32 `json:"invoice_generation_days_delay,omitempty"`
	// Minimal amount required for invoice generation
	InvoiceAmountThreshold *float64 `json:"invoice_amount_threshold,omitempty"`
	// Number of days for payment terms on invoices
	DefaultPaymentTerms *int32 `json:"default_payment_terms,omitempty"`
	Details *BillingDetails `json:"details,omitempty"`
	Payment *PaymentDetails `json:"payment,omitempty"`
}

// NewBillingInfo instantiates a new BillingInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingInfo() *BillingInfo {
	this := BillingInfo{}
	var isInvoiceCreationAuto bool = false
	this.IsInvoiceCreationAuto = &isInvoiceCreationAuto
	var defaultInvoiceIsHidden bool = false
	this.DefaultInvoiceIsHidden = &defaultInvoiceIsHidden
	var invoiceGenerationDaysDelay int32 = 0
	this.InvoiceGenerationDaysDelay = &invoiceGenerationDaysDelay
	var invoiceAmountThreshold float64 = 0
	this.InvoiceAmountThreshold = &invoiceAmountThreshold
	var defaultPaymentTerms int32 = 0
	this.DefaultPaymentTerms = &defaultPaymentTerms
	return &this
}

// NewBillingInfoWithDefaults instantiates a new BillingInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingInfoWithDefaults() *BillingInfo {
	this := BillingInfo{}
	var isInvoiceCreationAuto bool = false
	this.IsInvoiceCreationAuto = &isInvoiceCreationAuto
	var defaultInvoiceIsHidden bool = false
	this.DefaultInvoiceIsHidden = &defaultInvoiceIsHidden
	var invoiceGenerationDaysDelay int32 = 0
	this.InvoiceGenerationDaysDelay = &invoiceGenerationDaysDelay
	var invoiceAmountThreshold float64 = 0
	this.InvoiceAmountThreshold = &invoiceAmountThreshold
	var defaultPaymentTerms int32 = 0
	this.DefaultPaymentTerms = &defaultPaymentTerms
	return &this
}

// GetBillingFrequency returns the BillingFrequency field value if set, zero value otherwise.
func (o *BillingInfo) GetBillingFrequency() string {
	if o == nil || IsNil(o.BillingFrequency) {
		var ret string
		return ret
	}
	return *o.BillingFrequency
}

// GetBillingFrequencyOk returns a tuple with the BillingFrequency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInfo) GetBillingFrequencyOk() (*string, bool) {
	if o == nil || IsNil(o.BillingFrequency) {
		return nil, false
	}
	return o.BillingFrequency, true
}

// HasBillingFrequency returns a boolean if a field has been set.
func (o *BillingInfo) HasBillingFrequency() bool {
	if o != nil && !IsNil(o.BillingFrequency) {
		return true
	}

	return false
}

// SetBillingFrequency gets a reference to the given string and assigns it to the BillingFrequency field.
func (o *BillingInfo) SetBillingFrequency(v string) {
	o.BillingFrequency = &v
}

// GetPaymentType returns the PaymentType field value if set, zero value otherwise.
func (o *BillingInfo) GetPaymentType() string {
	if o == nil || IsNil(o.PaymentType) {
		var ret string
		return ret
	}
	return *o.PaymentType
}

// GetPaymentTypeOk returns a tuple with the PaymentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInfo) GetPaymentTypeOk() (*string, bool) {
	if o == nil || IsNil(o.PaymentType) {
		return nil, false
	}
	return o.PaymentType, true
}

// HasPaymentType returns a boolean if a field has been set.
func (o *BillingInfo) HasPaymentType() bool {
	if o != nil && !IsNil(o.PaymentType) {
		return true
	}

	return false
}

// SetPaymentType gets a reference to the given string and assigns it to the PaymentType field.
func (o *BillingInfo) SetPaymentType(v string) {
	o.PaymentType = &v
}

// GetTaxId returns the TaxId field value if set, zero value otherwise.
func (o *BillingInfo) GetTaxId() string {
	if o == nil || IsNil(o.TaxId) {
		var ret string
		return ret
	}
	return *o.TaxId
}

// GetTaxIdOk returns a tuple with the TaxId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInfo) GetTaxIdOk() (*string, bool) {
	if o == nil || IsNil(o.TaxId) {
		return nil, false
	}
	return o.TaxId, true
}

// HasTaxId returns a boolean if a field has been set.
func (o *BillingInfo) HasTaxId() bool {
	if o != nil && !IsNil(o.TaxId) {
		return true
	}

	return false
}

// SetTaxId gets a reference to the given string and assigns it to the TaxId field.
func (o *BillingInfo) SetTaxId(v string) {
	o.TaxId = &v
}

// GetIsInvoiceCreationAuto returns the IsInvoiceCreationAuto field value if set, zero value otherwise.
func (o *BillingInfo) GetIsInvoiceCreationAuto() bool {
	if o == nil || IsNil(o.IsInvoiceCreationAuto) {
		var ret bool
		return ret
	}
	return *o.IsInvoiceCreationAuto
}

// GetIsInvoiceCreationAutoOk returns a tuple with the IsInvoiceCreationAuto field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInfo) GetIsInvoiceCreationAutoOk() (*bool, bool) {
	if o == nil || IsNil(o.IsInvoiceCreationAuto) {
		return nil, false
	}
	return o.IsInvoiceCreationAuto, true
}

// HasIsInvoiceCreationAuto returns a boolean if a field has been set.
func (o *BillingInfo) HasIsInvoiceCreationAuto() bool {
	if o != nil && !IsNil(o.IsInvoiceCreationAuto) {
		return true
	}

	return false
}

// SetIsInvoiceCreationAuto gets a reference to the given bool and assigns it to the IsInvoiceCreationAuto field.
func (o *BillingInfo) SetIsInvoiceCreationAuto(v bool) {
	o.IsInvoiceCreationAuto = &v
}

// GetAutoInvoiceStartDate returns the AutoInvoiceStartDate field value if set, zero value otherwise.
func (o *BillingInfo) GetAutoInvoiceStartDate() string {
	if o == nil || IsNil(o.AutoInvoiceStartDate) {
		var ret string
		return ret
	}
	return *o.AutoInvoiceStartDate
}

// GetAutoInvoiceStartDateOk returns a tuple with the AutoInvoiceStartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInfo) GetAutoInvoiceStartDateOk() (*string, bool) {
	if o == nil || IsNil(o.AutoInvoiceStartDate) {
		return nil, false
	}
	return o.AutoInvoiceStartDate, true
}

// HasAutoInvoiceStartDate returns a boolean if a field has been set.
func (o *BillingInfo) HasAutoInvoiceStartDate() bool {
	if o != nil && !IsNil(o.AutoInvoiceStartDate) {
		return true
	}

	return false
}

// SetAutoInvoiceStartDate gets a reference to the given string and assigns it to the AutoInvoiceStartDate field.
func (o *BillingInfo) SetAutoInvoiceStartDate(v string) {
	o.AutoInvoiceStartDate = &v
}

// GetDefaultInvoiceIsHidden returns the DefaultInvoiceIsHidden field value if set, zero value otherwise.
func (o *BillingInfo) GetDefaultInvoiceIsHidden() bool {
	if o == nil || IsNil(o.DefaultInvoiceIsHidden) {
		var ret bool
		return ret
	}
	return *o.DefaultInvoiceIsHidden
}

// GetDefaultInvoiceIsHiddenOk returns a tuple with the DefaultInvoiceIsHidden field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInfo) GetDefaultInvoiceIsHiddenOk() (*bool, bool) {
	if o == nil || IsNil(o.DefaultInvoiceIsHidden) {
		return nil, false
	}
	return o.DefaultInvoiceIsHidden, true
}

// HasDefaultInvoiceIsHidden returns a boolean if a field has been set.
func (o *BillingInfo) HasDefaultInvoiceIsHidden() bool {
	if o != nil && !IsNil(o.DefaultInvoiceIsHidden) {
		return true
	}

	return false
}

// SetDefaultInvoiceIsHidden gets a reference to the given bool and assigns it to the DefaultInvoiceIsHidden field.
func (o *BillingInfo) SetDefaultInvoiceIsHidden(v bool) {
	o.DefaultInvoiceIsHidden = &v
}

// GetInvoiceGenerationDaysDelay returns the InvoiceGenerationDaysDelay field value if set, zero value otherwise.
func (o *BillingInfo) GetInvoiceGenerationDaysDelay() int32 {
	if o == nil || IsNil(o.InvoiceGenerationDaysDelay) {
		var ret int32
		return ret
	}
	return *o.InvoiceGenerationDaysDelay
}

// GetInvoiceGenerationDaysDelayOk returns a tuple with the InvoiceGenerationDaysDelay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInfo) GetInvoiceGenerationDaysDelayOk() (*int32, bool) {
	if o == nil || IsNil(o.InvoiceGenerationDaysDelay) {
		return nil, false
	}
	return o.InvoiceGenerationDaysDelay, true
}

// HasInvoiceGenerationDaysDelay returns a boolean if a field has been set.
func (o *BillingInfo) HasInvoiceGenerationDaysDelay() bool {
	if o != nil && !IsNil(o.InvoiceGenerationDaysDelay) {
		return true
	}

	return false
}

// SetInvoiceGenerationDaysDelay gets a reference to the given int32 and assigns it to the InvoiceGenerationDaysDelay field.
func (o *BillingInfo) SetInvoiceGenerationDaysDelay(v int32) {
	o.InvoiceGenerationDaysDelay = &v
}

// GetInvoiceAmountThreshold returns the InvoiceAmountThreshold field value if set, zero value otherwise.
func (o *BillingInfo) GetInvoiceAmountThreshold() float64 {
	if o == nil || IsNil(o.InvoiceAmountThreshold) {
		var ret float64
		return ret
	}
	return *o.InvoiceAmountThreshold
}

// GetInvoiceAmountThresholdOk returns a tuple with the InvoiceAmountThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInfo) GetInvoiceAmountThresholdOk() (*float64, bool) {
	if o == nil || IsNil(o.InvoiceAmountThreshold) {
		return nil, false
	}
	return o.InvoiceAmountThreshold, true
}

// HasInvoiceAmountThreshold returns a boolean if a field has been set.
func (o *BillingInfo) HasInvoiceAmountThreshold() bool {
	if o != nil && !IsNil(o.InvoiceAmountThreshold) {
		return true
	}

	return false
}

// SetInvoiceAmountThreshold gets a reference to the given float64 and assigns it to the InvoiceAmountThreshold field.
func (o *BillingInfo) SetInvoiceAmountThreshold(v float64) {
	o.InvoiceAmountThreshold = &v
}

// GetDefaultPaymentTerms returns the DefaultPaymentTerms field value if set, zero value otherwise.
func (o *BillingInfo) GetDefaultPaymentTerms() int32 {
	if o == nil || IsNil(o.DefaultPaymentTerms) {
		var ret int32
		return ret
	}
	return *o.DefaultPaymentTerms
}

// GetDefaultPaymentTermsOk returns a tuple with the DefaultPaymentTerms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInfo) GetDefaultPaymentTermsOk() (*int32, bool) {
	if o == nil || IsNil(o.DefaultPaymentTerms) {
		return nil, false
	}
	return o.DefaultPaymentTerms, true
}

// HasDefaultPaymentTerms returns a boolean if a field has been set.
func (o *BillingInfo) HasDefaultPaymentTerms() bool {
	if o != nil && !IsNil(o.DefaultPaymentTerms) {
		return true
	}

	return false
}

// SetDefaultPaymentTerms gets a reference to the given int32 and assigns it to the DefaultPaymentTerms field.
func (o *BillingInfo) SetDefaultPaymentTerms(v int32) {
	o.DefaultPaymentTerms = &v
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *BillingInfo) GetDetails() BillingDetails {
	if o == nil || IsNil(o.Details) {
		var ret BillingDetails
		return ret
	}
	return *o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInfo) GetDetailsOk() (*BillingDetails, bool) {
	if o == nil || IsNil(o.Details) {
		return nil, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *BillingInfo) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given BillingDetails and assigns it to the Details field.
func (o *BillingInfo) SetDetails(v BillingDetails) {
	o.Details = &v
}

// GetPayment returns the Payment field value if set, zero value otherwise.
func (o *BillingInfo) GetPayment() PaymentDetails {
	if o == nil || IsNil(o.Payment) {
		var ret PaymentDetails
		return ret
	}
	return *o.Payment
}

// GetPaymentOk returns a tuple with the Payment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingInfo) GetPaymentOk() (*PaymentDetails, bool) {
	if o == nil || IsNil(o.Payment) {
		return nil, false
	}
	return o.Payment, true
}

// HasPayment returns a boolean if a field has been set.
func (o *BillingInfo) HasPayment() bool {
	if o != nil && !IsNil(o.Payment) {
		return true
	}

	return false
}

// SetPayment gets a reference to the given PaymentDetails and assigns it to the Payment field.
func (o *BillingInfo) SetPayment(v PaymentDetails) {
	o.Payment = &v
}

func (o BillingInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BillingFrequency) {
		toSerialize["billing_frequency"] = o.BillingFrequency
	}
	if !IsNil(o.PaymentType) {
		toSerialize["payment_type"] = o.PaymentType
	}
	if !IsNil(o.TaxId) {
		toSerialize["tax_id"] = o.TaxId
	}
	if !IsNil(o.IsInvoiceCreationAuto) {
		toSerialize["is_invoice_creation_auto"] = o.IsInvoiceCreationAuto
	}
	if !IsNil(o.AutoInvoiceStartDate) {
		toSerialize["auto_invoice_start_date"] = o.AutoInvoiceStartDate
	}
	if !IsNil(o.DefaultInvoiceIsHidden) {
		toSerialize["default_invoice_is_hidden"] = o.DefaultInvoiceIsHidden
	}
	if !IsNil(o.InvoiceGenerationDaysDelay) {
		toSerialize["invoice_generation_days_delay"] = o.InvoiceGenerationDaysDelay
	}
	if !IsNil(o.InvoiceAmountThreshold) {
		toSerialize["invoice_amount_threshold"] = o.InvoiceAmountThreshold
	}
	if !IsNil(o.DefaultPaymentTerms) {
		toSerialize["default_payment_terms"] = o.DefaultPaymentTerms
	}
	if !IsNil(o.Details) {
		toSerialize["details"] = o.Details
	}
	if !IsNil(o.Payment) {
		toSerialize["payment"] = o.Payment
	}
	return toSerialize, nil
}

type NullableBillingInfo struct {
	value *BillingInfo
	isSet bool
}

func (v NullableBillingInfo) Get() *BillingInfo {
	return v.value
}

func (v *NullableBillingInfo) Set(val *BillingInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingInfo(val *BillingInfo) *NullableBillingInfo {
	return &NullableBillingInfo{value: val, isSet: true}
}

func (v NullableBillingInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


