/*
Everflow Affiliates API

API for managing affiliates in the Everflow platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package affiliate

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateAffiliateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAffiliateRequest{}

// CreateAffiliateRequest struct for CreateAffiliateRequest
type CreateAffiliateRequest struct {
	// The name of the affiliate
	Name string `json:"name"`
	// The affiliate's account status
	AccountStatus string `json:"account_status"`
	// The employee id of the affiliate's account manager
	NetworkEmployeeId int32 `json:"network_employee_id"`
	// Internal notes for network usage
	InternalNotes *string `json:"internal_notes,omitempty"`
	// The affiliate's default currency (3-letter code)
	DefaultCurrencyId *string `json:"default_currency_id,omitempty"`
	// Whether to allow affiliate to pass and override cost in their tracking links
	EnableMediaCostTrackingLinks *bool `json:"enable_media_cost_tracking_links,omitempty"`
	// The id of the affiliate that referred the new affiliate
	ReferrerId *int32 `json:"referrer_id,omitempty"`
	// Whether to include a contact address for this affiliate
	IsContactAddressEnabled *bool `json:"is_contact_address_enabled,omitempty"`
	// The ID of the Affiliate Tier
	NetworkAffiliateTierId *int32          `json:"network_affiliate_tier_id,omitempty"`
	ContactAddress         *ContactAddress `json:"contact_address,omitempty"`
	// Labels to associate with the affiliate
	Labels []string `json:"labels,omitempty"`
	// List of affiliate users to be created
	Users   []AffiliateUser `json:"users,omitempty"`
	Billing *BillingInfo    `json:"billing,omitempty"`
}

type _CreateAffiliateRequest CreateAffiliateRequest

// NewCreateAffiliateRequest instantiates a new CreateAffiliateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAffiliateRequest(name string, accountStatus string, networkEmployeeId int32) *CreateAffiliateRequest {
	this := CreateAffiliateRequest{}
	this.Name = name
	this.AccountStatus = accountStatus
	this.NetworkEmployeeId = networkEmployeeId
	var enableMediaCostTrackingLinks bool = false
	this.EnableMediaCostTrackingLinks = &enableMediaCostTrackingLinks
	var referrerId int32 = 0
	this.ReferrerId = &referrerId
	var isContactAddressEnabled bool = false
	this.IsContactAddressEnabled = &isContactAddressEnabled
	return &this
}

// NewCreateAffiliateRequestWithDefaults instantiates a new CreateAffiliateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAffiliateRequestWithDefaults() *CreateAffiliateRequest {
	this := CreateAffiliateRequest{}
	var enableMediaCostTrackingLinks bool = false
	this.EnableMediaCostTrackingLinks = &enableMediaCostTrackingLinks
	var referrerId int32 = 0
	this.ReferrerId = &referrerId
	var isContactAddressEnabled bool = false
	this.IsContactAddressEnabled = &isContactAddressEnabled
	return &this
}

// GetName returns the Name field value
func (o *CreateAffiliateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateAffiliateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateAffiliateRequest) SetName(v string) {
	o.Name = v
}

// GetAccountStatus returns the AccountStatus field value
func (o *CreateAffiliateRequest) GetAccountStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccountStatus
}

// GetAccountStatusOk returns a tuple with the AccountStatus field value
// and a boolean to check if the value has been set.
func (o *CreateAffiliateRequest) GetAccountStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccountStatus, true
}

// SetAccountStatus sets field value
func (o *CreateAffiliateRequest) SetAccountStatus(v string) {
	o.AccountStatus = v
}

// GetNetworkEmployeeId returns the NetworkEmployeeId field value
func (o *CreateAffiliateRequest) GetNetworkEmployeeId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NetworkEmployeeId
}

// GetNetworkEmployeeIdOk returns a tuple with the NetworkEmployeeId field value
// and a boolean to check if the value has been set.
func (o *CreateAffiliateRequest) GetNetworkEmployeeIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetworkEmployeeId, true
}

// SetNetworkEmployeeId sets field value
func (o *CreateAffiliateRequest) SetNetworkEmployeeId(v int32) {
	o.NetworkEmployeeId = v
}

// GetInternalNotes returns the InternalNotes field value if set, zero value otherwise.
func (o *CreateAffiliateRequest) GetInternalNotes() string {
	if o == nil || IsNil(o.InternalNotes) {
		var ret string
		return ret
	}
	return *o.InternalNotes
}

// GetInternalNotesOk returns a tuple with the InternalNotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAffiliateRequest) GetInternalNotesOk() (*string, bool) {
	if o == nil || IsNil(o.InternalNotes) {
		return nil, false
	}
	return o.InternalNotes, true
}

// HasInternalNotes returns a boolean if a field has been set.
func (o *CreateAffiliateRequest) HasInternalNotes() bool {
	if o != nil && !IsNil(o.InternalNotes) {
		return true
	}

	return false
}

// SetInternalNotes gets a reference to the given string and assigns it to the InternalNotes field.
func (o *CreateAffiliateRequest) SetInternalNotes(v string) {
	o.InternalNotes = &v
}

// GetDefaultCurrencyId returns the DefaultCurrencyId field value if set, zero value otherwise.
func (o *CreateAffiliateRequest) GetDefaultCurrencyId() string {
	if o == nil || IsNil(o.DefaultCurrencyId) {
		var ret string
		return ret
	}
	return *o.DefaultCurrencyId
}

// GetDefaultCurrencyIdOk returns a tuple with the DefaultCurrencyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAffiliateRequest) GetDefaultCurrencyIdOk() (*string, bool) {
	if o == nil || IsNil(o.DefaultCurrencyId) {
		return nil, false
	}
	return o.DefaultCurrencyId, true
}

// HasDefaultCurrencyId returns a boolean if a field has been set.
func (o *CreateAffiliateRequest) HasDefaultCurrencyId() bool {
	if o != nil && !IsNil(o.DefaultCurrencyId) {
		return true
	}

	return false
}

// SetDefaultCurrencyId gets a reference to the given string and assigns it to the DefaultCurrencyId field.
func (o *CreateAffiliateRequest) SetDefaultCurrencyId(v string) {
	o.DefaultCurrencyId = &v
}

// GetEnableMediaCostTrackingLinks returns the EnableMediaCostTrackingLinks field value if set, zero value otherwise.
func (o *CreateAffiliateRequest) GetEnableMediaCostTrackingLinks() bool {
	if o == nil || IsNil(o.EnableMediaCostTrackingLinks) {
		var ret bool
		return ret
	}
	return *o.EnableMediaCostTrackingLinks
}

// GetEnableMediaCostTrackingLinksOk returns a tuple with the EnableMediaCostTrackingLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAffiliateRequest) GetEnableMediaCostTrackingLinksOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableMediaCostTrackingLinks) {
		return nil, false
	}
	return o.EnableMediaCostTrackingLinks, true
}

// HasEnableMediaCostTrackingLinks returns a boolean if a field has been set.
func (o *CreateAffiliateRequest) HasEnableMediaCostTrackingLinks() bool {
	if o != nil && !IsNil(o.EnableMediaCostTrackingLinks) {
		return true
	}

	return false
}

// SetEnableMediaCostTrackingLinks gets a reference to the given bool and assigns it to the EnableMediaCostTrackingLinks field.
func (o *CreateAffiliateRequest) SetEnableMediaCostTrackingLinks(v bool) {
	o.EnableMediaCostTrackingLinks = &v
}

// GetReferrerId returns the ReferrerId field value if set, zero value otherwise.
func (o *CreateAffiliateRequest) GetReferrerId() int32 {
	if o == nil || IsNil(o.ReferrerId) {
		var ret int32
		return ret
	}
	return *o.ReferrerId
}

// GetReferrerIdOk returns a tuple with the ReferrerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAffiliateRequest) GetReferrerIdOk() (*int32, bool) {
	if o == nil || IsNil(o.ReferrerId) {
		return nil, false
	}
	return o.ReferrerId, true
}

// HasReferrerId returns a boolean if a field has been set.
func (o *CreateAffiliateRequest) HasReferrerId() bool {
	if o != nil && !IsNil(o.ReferrerId) {
		return true
	}

	return false
}

// SetReferrerId gets a reference to the given int32 and assigns it to the ReferrerId field.
func (o *CreateAffiliateRequest) SetReferrerId(v int32) {
	o.ReferrerId = &v
}

// GetIsContactAddressEnabled returns the IsContactAddressEnabled field value if set, zero value otherwise.
func (o *CreateAffiliateRequest) GetIsContactAddressEnabled() bool {
	if o == nil || IsNil(o.IsContactAddressEnabled) {
		var ret bool
		return ret
	}
	return *o.IsContactAddressEnabled
}

// GetIsContactAddressEnabledOk returns a tuple with the IsContactAddressEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAffiliateRequest) GetIsContactAddressEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsContactAddressEnabled) {
		return nil, false
	}
	return o.IsContactAddressEnabled, true
}

// HasIsContactAddressEnabled returns a boolean if a field has been set.
func (o *CreateAffiliateRequest) HasIsContactAddressEnabled() bool {
	if o != nil && !IsNil(o.IsContactAddressEnabled) {
		return true
	}

	return false
}

// SetIsContactAddressEnabled gets a reference to the given bool and assigns it to the IsContactAddressEnabled field.
func (o *CreateAffiliateRequest) SetIsContactAddressEnabled(v bool) {
	o.IsContactAddressEnabled = &v
}

// GetNetworkAffiliateTierId returns the NetworkAffiliateTierId field value if set, zero value otherwise.
func (o *CreateAffiliateRequest) GetNetworkAffiliateTierId() int32 {
	if o == nil || IsNil(o.NetworkAffiliateTierId) {
		var ret int32
		return ret
	}
	return *o.NetworkAffiliateTierId
}

// GetNetworkAffiliateTierIdOk returns a tuple with the NetworkAffiliateTierId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAffiliateRequest) GetNetworkAffiliateTierIdOk() (*int32, bool) {
	if o == nil || IsNil(o.NetworkAffiliateTierId) {
		return nil, false
	}
	return o.NetworkAffiliateTierId, true
}

// HasNetworkAffiliateTierId returns a boolean if a field has been set.
func (o *CreateAffiliateRequest) HasNetworkAffiliateTierId() bool {
	if o != nil && !IsNil(o.NetworkAffiliateTierId) {
		return true
	}

	return false
}

// SetNetworkAffiliateTierId gets a reference to the given int32 and assigns it to the NetworkAffiliateTierId field.
func (o *CreateAffiliateRequest) SetNetworkAffiliateTierId(v int32) {
	o.NetworkAffiliateTierId = &v
}

// GetContactAddress returns the ContactAddress field value if set, zero value otherwise.
func (o *CreateAffiliateRequest) GetContactAddress() ContactAddress {
	if o == nil || IsNil(o.ContactAddress) {
		var ret ContactAddress
		return ret
	}
	return *o.ContactAddress
}

// GetContactAddressOk returns a tuple with the ContactAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAffiliateRequest) GetContactAddressOk() (*ContactAddress, bool) {
	if o == nil || IsNil(o.ContactAddress) {
		return nil, false
	}
	return o.ContactAddress, true
}

// HasContactAddress returns a boolean if a field has been set.
func (o *CreateAffiliateRequest) HasContactAddress() bool {
	if o != nil && !IsNil(o.ContactAddress) {
		return true
	}

	return false
}

// SetContactAddress gets a reference to the given ContactAddress and assigns it to the ContactAddress field.
func (o *CreateAffiliateRequest) SetContactAddress(v ContactAddress) {
	o.ContactAddress = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *CreateAffiliateRequest) GetLabels() []string {
	if o == nil || IsNil(o.Labels) {
		var ret []string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAffiliateRequest) GetLabelsOk() ([]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *CreateAffiliateRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given []string and assigns it to the Labels field.
func (o *CreateAffiliateRequest) SetLabels(v []string) {
	o.Labels = v
}

// GetUsers returns the Users field value if set, zero value otherwise.
func (o *CreateAffiliateRequest) GetUsers() []AffiliateUser {
	if o == nil || IsNil(o.Users) {
		var ret []AffiliateUser
		return ret
	}
	return o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAffiliateRequest) GetUsersOk() ([]AffiliateUser, bool) {
	if o == nil || IsNil(o.Users) {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *CreateAffiliateRequest) HasUsers() bool {
	if o != nil && !IsNil(o.Users) {
		return true
	}

	return false
}

// SetUsers gets a reference to the given []AffiliateUser and assigns it to the Users field.
func (o *CreateAffiliateRequest) SetUsers(v []AffiliateUser) {
	o.Users = v
}

// GetBilling returns the Billing field value if set, zero value otherwise.
func (o *CreateAffiliateRequest) GetBilling() BillingInfo {
	if o == nil || IsNil(o.Billing) {
		var ret BillingInfo
		return ret
	}
	return *o.Billing
}

// GetBillingOk returns a tuple with the Billing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAffiliateRequest) GetBillingOk() (*BillingInfo, bool) {
	if o == nil || IsNil(o.Billing) {
		return nil, false
	}
	return o.Billing, true
}

// HasBilling returns a boolean if a field has been set.
func (o *CreateAffiliateRequest) HasBilling() bool {
	if o != nil && !IsNil(o.Billing) {
		return true
	}

	return false
}

// SetBilling gets a reference to the given BillingInfo and assigns it to the Billing field.
func (o *CreateAffiliateRequest) SetBilling(v BillingInfo) {
	o.Billing = &v
}

func (o CreateAffiliateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAffiliateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["account_status"] = o.AccountStatus
	toSerialize["network_employee_id"] = o.NetworkEmployeeId
	if !IsNil(o.InternalNotes) {
		toSerialize["internal_notes"] = o.InternalNotes
	}
	if !IsNil(o.DefaultCurrencyId) {
		toSerialize["default_currency_id"] = o.DefaultCurrencyId
	}
	if !IsNil(o.EnableMediaCostTrackingLinks) {
		toSerialize["enable_media_cost_tracking_links"] = o.EnableMediaCostTrackingLinks
	}
	if !IsNil(o.ReferrerId) {
		toSerialize["referrer_id"] = o.ReferrerId
	}
	if !IsNil(o.IsContactAddressEnabled) {
		toSerialize["is_contact_address_enabled"] = o.IsContactAddressEnabled
	}
	if !IsNil(o.NetworkAffiliateTierId) {
		toSerialize["network_affiliate_tier_id"] = o.NetworkAffiliateTierId
	}
	if !IsNil(o.ContactAddress) {
		toSerialize["contact_address"] = o.ContactAddress
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Users) {
		toSerialize["users"] = o.Users
	}
	if !IsNil(o.Billing) {
		toSerialize["billing"] = o.Billing
	}
	return toSerialize, nil
}

func (o *CreateAffiliateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"account_status",
		"network_employee_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAffiliateRequest := _CreateAffiliateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateAffiliateRequest)

	if err != nil {
		return err
	}

	*o = CreateAffiliateRequest(varCreateAffiliateRequest)

	return err
}

type NullableCreateAffiliateRequest struct {
	value *CreateAffiliateRequest
	isSet bool
}

func (v NullableCreateAffiliateRequest) Get() *CreateAffiliateRequest {
	return v.value
}

func (v *NullableCreateAffiliateRequest) Set(val *CreateAffiliateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAffiliateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAffiliateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAffiliateRequest(val *CreateAffiliateRequest) *NullableCreateAffiliateRequest {
	return &NullableCreateAffiliateRequest{value: val, isSet: true}
}

func (v NullableCreateAffiliateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAffiliateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
