/*
Everflow Network API - Offers

Testing OffersAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package offer

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_offer_OffersAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test OffersAPIService CreateOffer", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.OffersAPI.CreateOffer(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OffersAPIService GetOfferById", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var offerId int32

		resp, httpRes, err := apiClient.OffersAPI.GetOfferById(context.Background(), offerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OffersAPIService UpdateOffer", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var offerId int32

		resp, httpRes, err := apiClient.OffersAPI.UpdateOffer(context.Background(), offerId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
