apiVersion: apps/v1
kind: Deployment
metadata:
  name: affiliate-backend
  namespace: saas-bff
  labels:
    app: affiliate-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: affiliate-backend
  template:
    metadata:
      labels:
        app: affiliate-backend
    spec:
      containers:
      - name: app
        image: europe-west1-docker.pkg.dev/jinko-test/jinko-test-docker-repo/saas-app:0.0.1
        args:
          - "--mock-mode"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: HOST
          value: "0.0.0.0"
        - name: DATABASE_HOST
          value: "127.0.0.1"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: saas-bff-db-credentials
              key: db_user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: saas-bff-db-credentials
              key: db_password
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: saas-bff-db-credentials
              key: db_name
        - name: DATABASE_SSLMODE
          value: "disable"
        - name: LOG_LEVEL
          value: "info"
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: saas-bff-secrets
              key: supabase_url
        - name: SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: saas-bff-secrets
              key: supabase_anon_key
        - name: SUPABASE_SERVICE_ROLE_KEY
          valueFrom:
            secretKeyRef:
              name: saas-bff-secrets
              key: supabase_service_role_key
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: saas-bff-secrets
              key: jwt_secret
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      # Cloud SQL Proxy sidecar container
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.1.0
        args:
          - "--structured-logs"
          - "--port=5432"
          - "--auto-iam-authn"
          - "--private-ip"
          - "$(CONNECTION_NAME)"
        env:
        - name: CONNECTION_NAME
          valueFrom:
            secretKeyRef:
              name: saas-bff-db-credentials
              key: connection_name
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        securityContext:
          runAsNonRoot: true