/*
Everflow Network API - Offers

API for managing offers in the Everflow platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package offer

import (
	"encoding/json"
)

// checks if the IntegrationsAnura type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntegrationsAnura{}

// IntegrationsAnura struct for IntegrationsAnura
type IntegrationsAnura struct {
	// Anura enabled
	Enabled *bool `json:"enabled,omitempty"`
}

// NewIntegrationsAnura instantiates a new IntegrationsAnura object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntegrationsAnura() *IntegrationsAnura {
	this := IntegrationsAnura{}
	return &this
}

// NewIntegrationsAnuraWithDefaults instantiates a new IntegrationsAnura object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntegrationsAnuraWithDefaults() *IntegrationsAnura {
	this := IntegrationsAnura{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *IntegrationsAnura) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationsAnura) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *IntegrationsAnura) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *IntegrationsAnura) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o IntegrationsAnura) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntegrationsAnura) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	return toSerialize, nil
}

type NullableIntegrationsAnura struct {
	value *IntegrationsAnura
	isSet bool
}

func (v NullableIntegrationsAnura) Get() *IntegrationsAnura {
	return v.value
}

func (v *NullableIntegrationsAnura) Set(val *IntegrationsAnura) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrationsAnura) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrationsAnura) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntegrationsAnura(val *IntegrationsAnura) *NullableIntegrationsAnura {
	return &NullableIntegrationsAnura{value: val, isSet: true}
}

func (v NullableIntegrationsAnura) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrationsAnura) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


