/*
Everflow Network API - Offers

API for managing offers in the Everflow platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package offer

import (
	"encoding/json"
)

// checks if the IntegrationsEzepo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntegrationsEzepo{}

// IntegrationsEzepo struct for IntegrationsEzepo
type IntegrationsEzepo struct {
	// Ezepo enabled
	Enabled *bool `json:"enabled,omitempty"`
}

// NewIntegrationsEzepo instantiates a new IntegrationsEzepo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntegrationsEzepo() *IntegrationsEzepo {
	this := IntegrationsEzepo{}
	return &this
}

// NewIntegrationsEzepoWithDefaults instantiates a new IntegrationsEzepo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntegrationsEzepoWithDefaults() *IntegrationsEzepo {
	this := IntegrationsEzepo{}
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *IntegrationsEzepo) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationsEzepo) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *IntegrationsEzepo) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *IntegrationsEzepo) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o IntegrationsEzepo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntegrationsEzepo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	return toSerialize, nil
}

type NullableIntegrationsEzepo struct {
	value *IntegrationsEzepo
	isSet bool
}

func (v NullableIntegrationsEzepo) Get() *IntegrationsEzepo {
	return v.value
}

func (v *NullableIntegrationsEzepo) Set(val *IntegrationsEzepo) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrationsEzepo) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrationsEzepo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntegrationsEzepo(val *IntegrationsEzepo) *NullableIntegrationsEzepo {
	return &NullableIntegrationsEzepo{value: val, isSet: true}
}

func (v NullableIntegrationsEzepo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrationsEzepo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


