/*
Everflow Network API - Offers

API for managing offers in the Everflow platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package offer

import (
	"encoding/json"
)

// checks if the InternalRedirect type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InternalRedirect{}

// InternalRedirect struct for InternalRedirect
type InternalRedirect struct {
	// Offer ID to redirect to
	RedirectNetworkOfferId *int32 `json:"redirect_network_offer_id,omitempty"`
	// Offer URL ID (0 for default)
	RedirectNetworkOfferUrlId *int32 `json:"redirect_network_offer_url_id,omitempty"`
	// Offer group ID to redirect to
	RedirectNetworkOfferGroupId *int32 `json:"redirect_network_offer_group_id,omitempty"`
	// Campaign ID to redirect to
	RedirectNetworkCampaignId *int32 `json:"redirect_network_campaign_id,omitempty"`
	// Priority or weight value
	RoutingValue *int32   `json:"routing_value,omitempty"`
	Ruleset      *Ruleset `json:"ruleset,omitempty"`
	// Fail traffic categories
	Categories []string `json:"categories,omitempty"`
	// Whether to pay affiliate
	IsPayAffiliate *bool `json:"is_pay_affiliate,omitempty"`
	// Whether to pass through to destination
	IsPassThrough *bool `json:"is_pass_through,omitempty"`
	// Whether to apply to specific affiliates
	IsApplySpecificAffiliates *bool `json:"is_apply_specific_affiliates,omitempty"`
	// Specific affiliate IDs
	NetworkAffiliateIds []int32 `json:"network_affiliate_ids,omitempty"`
}

// NewInternalRedirect instantiates a new InternalRedirect object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInternalRedirect() *InternalRedirect {
	this := InternalRedirect{}
	var isPayAffiliate bool = false
	this.IsPayAffiliate = &isPayAffiliate
	var isPassThrough bool = false
	this.IsPassThrough = &isPassThrough
	var isApplySpecificAffiliates bool = false
	this.IsApplySpecificAffiliates = &isApplySpecificAffiliates
	return &this
}

// NewInternalRedirectWithDefaults instantiates a new InternalRedirect object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInternalRedirectWithDefaults() *InternalRedirect {
	this := InternalRedirect{}
	var isPayAffiliate bool = false
	this.IsPayAffiliate = &isPayAffiliate
	var isPassThrough bool = false
	this.IsPassThrough = &isPassThrough
	var isApplySpecificAffiliates bool = false
	this.IsApplySpecificAffiliates = &isApplySpecificAffiliates
	return &this
}

// GetRedirectNetworkOfferId returns the RedirectNetworkOfferId field value if set, zero value otherwise.
func (o *InternalRedirect) GetRedirectNetworkOfferId() int32 {
	if o == nil || IsNil(o.RedirectNetworkOfferId) {
		var ret int32
		return ret
	}
	return *o.RedirectNetworkOfferId
}

// GetRedirectNetworkOfferIdOk returns a tuple with the RedirectNetworkOfferId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalRedirect) GetRedirectNetworkOfferIdOk() (*int32, bool) {
	if o == nil || IsNil(o.RedirectNetworkOfferId) {
		return nil, false
	}
	return o.RedirectNetworkOfferId, true
}

// HasRedirectNetworkOfferId returns a boolean if a field has been set.
func (o *InternalRedirect) HasRedirectNetworkOfferId() bool {
	if o != nil && !IsNil(o.RedirectNetworkOfferId) {
		return true
	}

	return false
}

// SetRedirectNetworkOfferId gets a reference to the given int32 and assigns it to the RedirectNetworkOfferId field.
func (o *InternalRedirect) SetRedirectNetworkOfferId(v int32) {
	o.RedirectNetworkOfferId = &v
}

// GetRedirectNetworkOfferUrlId returns the RedirectNetworkOfferUrlId field value if set, zero value otherwise.
func (o *InternalRedirect) GetRedirectNetworkOfferUrlId() int32 {
	if o == nil || IsNil(o.RedirectNetworkOfferUrlId) {
		var ret int32
		return ret
	}
	return *o.RedirectNetworkOfferUrlId
}

// GetRedirectNetworkOfferUrlIdOk returns a tuple with the RedirectNetworkOfferUrlId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalRedirect) GetRedirectNetworkOfferUrlIdOk() (*int32, bool) {
	if o == nil || IsNil(o.RedirectNetworkOfferUrlId) {
		return nil, false
	}
	return o.RedirectNetworkOfferUrlId, true
}

// HasRedirectNetworkOfferUrlId returns a boolean if a field has been set.
func (o *InternalRedirect) HasRedirectNetworkOfferUrlId() bool {
	if o != nil && !IsNil(o.RedirectNetworkOfferUrlId) {
		return true
	}

	return false
}

// SetRedirectNetworkOfferUrlId gets a reference to the given int32 and assigns it to the RedirectNetworkOfferUrlId field.
func (o *InternalRedirect) SetRedirectNetworkOfferUrlId(v int32) {
	o.RedirectNetworkOfferUrlId = &v
}

// GetRedirectNetworkOfferGroupId returns the RedirectNetworkOfferGroupId field value if set, zero value otherwise.
func (o *InternalRedirect) GetRedirectNetworkOfferGroupId() int32 {
	if o == nil || IsNil(o.RedirectNetworkOfferGroupId) {
		var ret int32
		return ret
	}
	return *o.RedirectNetworkOfferGroupId
}

// GetRedirectNetworkOfferGroupIdOk returns a tuple with the RedirectNetworkOfferGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalRedirect) GetRedirectNetworkOfferGroupIdOk() (*int32, bool) {
	if o == nil || IsNil(o.RedirectNetworkOfferGroupId) {
		return nil, false
	}
	return o.RedirectNetworkOfferGroupId, true
}

// HasRedirectNetworkOfferGroupId returns a boolean if a field has been set.
func (o *InternalRedirect) HasRedirectNetworkOfferGroupId() bool {
	if o != nil && !IsNil(o.RedirectNetworkOfferGroupId) {
		return true
	}

	return false
}

// SetRedirectNetworkOfferGroupId gets a reference to the given int32 and assigns it to the RedirectNetworkOfferGroupId field.
func (o *InternalRedirect) SetRedirectNetworkOfferGroupId(v int32) {
	o.RedirectNetworkOfferGroupId = &v
}

// GetRedirectNetworkCampaignId returns the RedirectNetworkCampaignId field value if set, zero value otherwise.
func (o *InternalRedirect) GetRedirectNetworkCampaignId() int32 {
	if o == nil || IsNil(o.RedirectNetworkCampaignId) {
		var ret int32
		return ret
	}
	return *o.RedirectNetworkCampaignId
}

// GetRedirectNetworkCampaignIdOk returns a tuple with the RedirectNetworkCampaignId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalRedirect) GetRedirectNetworkCampaignIdOk() (*int32, bool) {
	if o == nil || IsNil(o.RedirectNetworkCampaignId) {
		return nil, false
	}
	return o.RedirectNetworkCampaignId, true
}

// HasRedirectNetworkCampaignId returns a boolean if a field has been set.
func (o *InternalRedirect) HasRedirectNetworkCampaignId() bool {
	if o != nil && !IsNil(o.RedirectNetworkCampaignId) {
		return true
	}

	return false
}

// SetRedirectNetworkCampaignId gets a reference to the given int32 and assigns it to the RedirectNetworkCampaignId field.
func (o *InternalRedirect) SetRedirectNetworkCampaignId(v int32) {
	o.RedirectNetworkCampaignId = &v
}

// GetRoutingValue returns the RoutingValue field value if set, zero value otherwise.
func (o *InternalRedirect) GetRoutingValue() int32 {
	if o == nil || IsNil(o.RoutingValue) {
		var ret int32
		return ret
	}
	return *o.RoutingValue
}

// GetRoutingValueOk returns a tuple with the RoutingValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalRedirect) GetRoutingValueOk() (*int32, bool) {
	if o == nil || IsNil(o.RoutingValue) {
		return nil, false
	}
	return o.RoutingValue, true
}

// HasRoutingValue returns a boolean if a field has been set.
func (o *InternalRedirect) HasRoutingValue() bool {
	if o != nil && !IsNil(o.RoutingValue) {
		return true
	}

	return false
}

// SetRoutingValue gets a reference to the given int32 and assigns it to the RoutingValue field.
func (o *InternalRedirect) SetRoutingValue(v int32) {
	o.RoutingValue = &v
}

// GetRuleset returns the Ruleset field value if set, zero value otherwise.
func (o *InternalRedirect) GetRuleset() Ruleset {
	if o == nil || IsNil(o.Ruleset) {
		var ret Ruleset
		return ret
	}
	return *o.Ruleset
}

// GetRulesetOk returns a tuple with the Ruleset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalRedirect) GetRulesetOk() (*Ruleset, bool) {
	if o == nil || IsNil(o.Ruleset) {
		return nil, false
	}
	return o.Ruleset, true
}

// HasRuleset returns a boolean if a field has been set.
func (o *InternalRedirect) HasRuleset() bool {
	if o != nil && !IsNil(o.Ruleset) {
		return true
	}

	return false
}

// SetRuleset gets a reference to the given Ruleset and assigns it to the Ruleset field.
func (o *InternalRedirect) SetRuleset(v Ruleset) {
	o.Ruleset = &v
}

// GetCategories returns the Categories field value if set, zero value otherwise.
func (o *InternalRedirect) GetCategories() []string {
	if o == nil || IsNil(o.Categories) {
		var ret []string
		return ret
	}
	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalRedirect) GetCategoriesOk() ([]string, bool) {
	if o == nil || IsNil(o.Categories) {
		return nil, false
	}
	return o.Categories, true
}

// HasCategories returns a boolean if a field has been set.
func (o *InternalRedirect) HasCategories() bool {
	if o != nil && !IsNil(o.Categories) {
		return true
	}

	return false
}

// SetCategories gets a reference to the given []string and assigns it to the Categories field.
func (o *InternalRedirect) SetCategories(v []string) {
	o.Categories = v
}

// GetIsPayAffiliate returns the IsPayAffiliate field value if set, zero value otherwise.
func (o *InternalRedirect) GetIsPayAffiliate() bool {
	if o == nil || IsNil(o.IsPayAffiliate) {
		var ret bool
		return ret
	}
	return *o.IsPayAffiliate
}

// GetIsPayAffiliateOk returns a tuple with the IsPayAffiliate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalRedirect) GetIsPayAffiliateOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPayAffiliate) {
		return nil, false
	}
	return o.IsPayAffiliate, true
}

// HasIsPayAffiliate returns a boolean if a field has been set.
func (o *InternalRedirect) HasIsPayAffiliate() bool {
	if o != nil && !IsNil(o.IsPayAffiliate) {
		return true
	}

	return false
}

// SetIsPayAffiliate gets a reference to the given bool and assigns it to the IsPayAffiliate field.
func (o *InternalRedirect) SetIsPayAffiliate(v bool) {
	o.IsPayAffiliate = &v
}

// GetIsPassThrough returns the IsPassThrough field value if set, zero value otherwise.
func (o *InternalRedirect) GetIsPassThrough() bool {
	if o == nil || IsNil(o.IsPassThrough) {
		var ret bool
		return ret
	}
	return *o.IsPassThrough
}

// GetIsPassThroughOk returns a tuple with the IsPassThrough field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalRedirect) GetIsPassThroughOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPassThrough) {
		return nil, false
	}
	return o.IsPassThrough, true
}

// HasIsPassThrough returns a boolean if a field has been set.
func (o *InternalRedirect) HasIsPassThrough() bool {
	if o != nil && !IsNil(o.IsPassThrough) {
		return true
	}

	return false
}

// SetIsPassThrough gets a reference to the given bool and assigns it to the IsPassThrough field.
func (o *InternalRedirect) SetIsPassThrough(v bool) {
	o.IsPassThrough = &v
}

// GetIsApplySpecificAffiliates returns the IsApplySpecificAffiliates field value if set, zero value otherwise.
func (o *InternalRedirect) GetIsApplySpecificAffiliates() bool {
	if o == nil || IsNil(o.IsApplySpecificAffiliates) {
		var ret bool
		return ret
	}
	return *o.IsApplySpecificAffiliates
}

// GetIsApplySpecificAffiliatesOk returns a tuple with the IsApplySpecificAffiliates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalRedirect) GetIsApplySpecificAffiliatesOk() (*bool, bool) {
	if o == nil || IsNil(o.IsApplySpecificAffiliates) {
		return nil, false
	}
	return o.IsApplySpecificAffiliates, true
}

// HasIsApplySpecificAffiliates returns a boolean if a field has been set.
func (o *InternalRedirect) HasIsApplySpecificAffiliates() bool {
	if o != nil && !IsNil(o.IsApplySpecificAffiliates) {
		return true
	}

	return false
}

// SetIsApplySpecificAffiliates gets a reference to the given bool and assigns it to the IsApplySpecificAffiliates field.
func (o *InternalRedirect) SetIsApplySpecificAffiliates(v bool) {
	o.IsApplySpecificAffiliates = &v
}

// GetNetworkAffiliateIds returns the NetworkAffiliateIds field value if set, zero value otherwise.
func (o *InternalRedirect) GetNetworkAffiliateIds() []int32 {
	if o == nil || IsNil(o.NetworkAffiliateIds) {
		var ret []int32
		return ret
	}
	return o.NetworkAffiliateIds
}

// GetNetworkAffiliateIdsOk returns a tuple with the NetworkAffiliateIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InternalRedirect) GetNetworkAffiliateIdsOk() ([]int32, bool) {
	if o == nil || IsNil(o.NetworkAffiliateIds) {
		return nil, false
	}
	return o.NetworkAffiliateIds, true
}

// HasNetworkAffiliateIds returns a boolean if a field has been set.
func (o *InternalRedirect) HasNetworkAffiliateIds() bool {
	if o != nil && !IsNil(o.NetworkAffiliateIds) {
		return true
	}

	return false
}

// SetNetworkAffiliateIds gets a reference to the given []int32 and assigns it to the NetworkAffiliateIds field.
func (o *InternalRedirect) SetNetworkAffiliateIds(v []int32) {
	o.NetworkAffiliateIds = v
}

func (o InternalRedirect) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InternalRedirect) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RedirectNetworkOfferId) {
		toSerialize["redirect_network_offer_id"] = o.RedirectNetworkOfferId
	}
	if !IsNil(o.RedirectNetworkOfferUrlId) {
		toSerialize["redirect_network_offer_url_id"] = o.RedirectNetworkOfferUrlId
	}
	if !IsNil(o.RedirectNetworkOfferGroupId) {
		toSerialize["redirect_network_offer_group_id"] = o.RedirectNetworkOfferGroupId
	}
	if !IsNil(o.RedirectNetworkCampaignId) {
		toSerialize["redirect_network_campaign_id"] = o.RedirectNetworkCampaignId
	}
	if !IsNil(o.RoutingValue) {
		toSerialize["routing_value"] = o.RoutingValue
	}
	if !IsNil(o.Ruleset) {
		toSerialize["ruleset"] = o.Ruleset
	}
	if !IsNil(o.Categories) {
		toSerialize["categories"] = o.Categories
	}
	if !IsNil(o.IsPayAffiliate) {
		toSerialize["is_pay_affiliate"] = o.IsPayAffiliate
	}
	if !IsNil(o.IsPassThrough) {
		toSerialize["is_pass_through"] = o.IsPassThrough
	}
	if !IsNil(o.IsApplySpecificAffiliates) {
		toSerialize["is_apply_specific_affiliates"] = o.IsApplySpecificAffiliates
	}
	if !IsNil(o.NetworkAffiliateIds) {
		toSerialize["network_affiliate_ids"] = o.NetworkAffiliateIds
	}
	return toSerialize, nil
}

type NullableInternalRedirect struct {
	value *InternalRedirect
	isSet bool
}

func (v NullableInternalRedirect) Get() *InternalRedirect {
	return v.value
}

func (v *NullableInternalRedirect) Set(val *InternalRedirect) {
	v.value = val
	v.isSet = true
}

func (v NullableInternalRedirect) IsSet() bool {
	return v.isSet
}

func (v *NullableInternalRedirect) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInternalRedirect(val *InternalRedirect) *NullableInternalRedirect {
	return &NullableInternalRedirect{value: val, isSet: true}
}

func (v NullableInternalRedirect) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInternalRedirect) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
