/*
Everflow Network API - Offers

API for managing offers in the Everflow platform

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package offer

import (
	"encoding/json"
)

// checks if the IntegrationsTwentyfourMetrics type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntegrationsTwentyfourMetrics{}

// IntegrationsTwentyfourMetrics struct for IntegrationsTwentyfourMetrics
type IntegrationsTwentyfourMetrics struct {
	// 24metrics tracker ID
	NetworkIntegrationTwentyfourMetricsTrackerId *int32 `json:"network_integration_twentyfour_metrics_tracker_id,omitempty"`
}

// NewIntegrationsTwentyfourMetrics instantiates a new IntegrationsTwentyfourMetrics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntegrationsTwentyfourMetrics() *IntegrationsTwentyfourMetrics {
	this := IntegrationsTwentyfourMetrics{}
	return &this
}

// NewIntegrationsTwentyfourMetricsWithDefaults instantiates a new IntegrationsTwentyfourMetrics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntegrationsTwentyfourMetricsWithDefaults() *IntegrationsTwentyfourMetrics {
	this := IntegrationsTwentyfourMetrics{}
	return &this
}

// GetNetworkIntegrationTwentyfourMetricsTrackerId returns the NetworkIntegrationTwentyfourMetricsTrackerId field value if set, zero value otherwise.
func (o *IntegrationsTwentyfourMetrics) GetNetworkIntegrationTwentyfourMetricsTrackerId() int32 {
	if o == nil || IsNil(o.NetworkIntegrationTwentyfourMetricsTrackerId) {
		var ret int32
		return ret
	}
	return *o.NetworkIntegrationTwentyfourMetricsTrackerId
}

// GetNetworkIntegrationTwentyfourMetricsTrackerIdOk returns a tuple with the NetworkIntegrationTwentyfourMetricsTrackerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IntegrationsTwentyfourMetrics) GetNetworkIntegrationTwentyfourMetricsTrackerIdOk() (*int32, bool) {
	if o == nil || IsNil(o.NetworkIntegrationTwentyfourMetricsTrackerId) {
		return nil, false
	}
	return o.NetworkIntegrationTwentyfourMetricsTrackerId, true
}

// HasNetworkIntegrationTwentyfourMetricsTrackerId returns a boolean if a field has been set.
func (o *IntegrationsTwentyfourMetrics) HasNetworkIntegrationTwentyfourMetricsTrackerId() bool {
	if o != nil && !IsNil(o.NetworkIntegrationTwentyfourMetricsTrackerId) {
		return true
	}

	return false
}

// SetNetworkIntegrationTwentyfourMetricsTrackerId gets a reference to the given int32 and assigns it to the NetworkIntegrationTwentyfourMetricsTrackerId field.
func (o *IntegrationsTwentyfourMetrics) SetNetworkIntegrationTwentyfourMetricsTrackerId(v int32) {
	o.NetworkIntegrationTwentyfourMetricsTrackerId = &v
}

func (o IntegrationsTwentyfourMetrics) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntegrationsTwentyfourMetrics) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NetworkIntegrationTwentyfourMetricsTrackerId) {
		toSerialize["network_integration_twentyfour_metrics_tracker_id"] = o.NetworkIntegrationTwentyfourMetricsTrackerId
	}
	return toSerialize, nil
}

type NullableIntegrationsTwentyfourMetrics struct {
	value *IntegrationsTwentyfourMetrics
	isSet bool
}

func (v NullableIntegrationsTwentyfourMetrics) Get() *IntegrationsTwentyfourMetrics {
	return v.value
}

func (v *NullableIntegrationsTwentyfourMetrics) Set(val *IntegrationsTwentyfourMetrics) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrationsTwentyfourMetrics) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrationsTwentyfourMetrics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntegrationsTwentyfourMetrics(val *IntegrationsTwentyfourMetrics) *NullableIntegrationsTwentyfourMetrics {
	return &NullableIntegrationsTwentyfourMetrics{value: val, isSet: true}
}

func (v NullableIntegrationsTwentyfourMetrics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrationsTwentyfourMetrics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


